#!/usr/bin/env bash
set -euo pipefail

# Check if the script is run from the root of the PasVulkan GIT repository by checking if the .git directory is present
if [ ! -d ".git" ]; then
  echo "This script must be run from the root of the PasVulkan GIT repository"
  exit 1
fi

# Check if the script is run from the original author by checking if the home directory /home/bero is present, which is the home directory of the original author
if [ ! -d "/home/bero" ]; then
  echo "This script must be run only from the original author"
  exit 1
fi

read -p "Enter commit message (or leave blank for default): " commit_message

if [ -z "$commit_message" ]; then
  commit_message="More work"
fi

# Save the current directory in a variable
OLD_DIR="$(pwd)"

# Copy modified files from the pashtmldown submodule to the real directory of the pashtmldown GIT repository
cp -f externals/pashtmldown/README.md ../pashtmldown/README.md
cp -f externals/pashtmldown/src/PasHTMLDown.pas ../pashtmldown/src/PasHTMLDown.pas
cp -f externals/pashtmldown/src/PasHTMLDownCanvasRenderer.pas ../pashtmldown/src/PasHTMLDownCanvasRenderer.pas

# Clean the pashtmldown submodule from the local changes
cd externals/pashtmldown
git stash # Stash the local changes
git stash drop # Drop the stashed local changes
git pull origin master # For ensuring that the local pashtmldown submodule is on the right branch
cd "${OLD_DIR}"

# Commit the changes in the pashtmldown GIT repository
cd ../pashtmldown
git commit -a -m "$commit_message"
git push
cd "${OLD_DIR}"

# Update all submodules including the pashtmldown submodule for the lastest versions
git submodule update --remote --recursive

# Commit the changes in the main PasVulkan GIT repository
git commit -am "Updated submodules"
git push

# Switch to the old directory back
cd "${OLD_DIR}"

# Exit with success
exit 0
