private
function GetBB:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBG:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBR:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGB:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGG:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGR:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPP:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPS:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPST:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPT:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRB:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRG:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRR:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSP:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSS:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSST:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetST:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTP:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTS:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTST:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTT:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXX:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXY:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZ:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYX:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYY:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZ:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZX:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZY:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZ:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBG(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBGR(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBR(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBRG(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGB(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGBR(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGR(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGRB(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPS(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPST(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPT(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPTS(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRB(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRBG(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRG(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRGB(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSP(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSPT(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetST(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSTP(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTP(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTPS(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTS(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTSP(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXY(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXYZ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZ(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZY(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYX(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYXZ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZ(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZX(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZX(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZXY(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZY(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZYX(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
public
property bb:TVector2 read GetBB;
property bbb:TVector3 read GetBBB;
property bbg:TVector3 read GetBBG;
property bbr:TVector3 read GetBBR;
property bg:TVector2 read GetBG write SetBG;
property bgb:TVector3 read GetBGB;
property bgg:TVector3 read GetBGG;
property bgr:TVector3 read GetBGR write SetBGR;
property br:TVector2 read GetBR write SetBR;
property brb:TVector3 read GetBRB;
property brg:TVector3 read GetBRG write SetBRG;
property brr:TVector3 read GetBRR;
property gb:TVector2 read GetGB write SetGB;
property gbb:TVector3 read GetGBB;
property gbg:TVector3 read GetGBG;
property gbr:TVector3 read GetGBR write SetGBR;
property gg:TVector2 read GetGG;
property ggb:TVector3 read GetGGB;
property ggg:TVector3 read GetGGG;
property ggr:TVector3 read GetGGR;
property gr:TVector2 read GetGR write SetGR;
property grb:TVector3 read GetGRB write SetGRB;
property grg:TVector3 read GetGRG;
property grr:TVector3 read GetGRR;
property pp:TVector2 read GetPP;
property ppp:TVector3 read GetPPP;
property pps:TVector3 read GetPPS;
property ppt:TVector3 read GetPPT;
property ps:TVector2 read GetPS write SetPS;
property psp:TVector3 read GetPSP;
property pss:TVector3 read GetPSS;
property pst:TVector3 read GetPST write SetPST;
property pt:TVector2 read GetPT write SetPT;
property ptp:TVector3 read GetPTP;
property pts:TVector3 read GetPTS write SetPTS;
property ptt:TVector3 read GetPTT;
property rb:TVector2 read GetRB write SetRB;
property rbb:TVector3 read GetRBB;
property rbg:TVector3 read GetRBG write SetRBG;
property rbr:TVector3 read GetRBR;
property rg:TVector2 read GetRG write SetRG;
property rgb:TVector3 read GetRGB write SetRGB;
property rgg:TVector3 read GetRGG;
property rgr:TVector3 read GetRGR;
property rr:TVector2 read GetRR;
property rrb:TVector3 read GetRRB;
property rrg:TVector3 read GetRRG;
property rrr:TVector3 read GetRRR;
property sp:TVector2 read GetSP write SetSP;
property spp:TVector3 read GetSPP;
property sps:TVector3 read GetSPS;
property spt:TVector3 read GetSPT write SetSPT;
property ss:TVector2 read GetSS;
property ssp:TVector3 read GetSSP;
property sss:TVector3 read GetSSS;
property sst:TVector3 read GetSST;
property st:TVector2 read GetST write SetST;
property stp:TVector3 read GetSTP write SetSTP;
property sts:TVector3 read GetSTS;
property stt:TVector3 read GetSTT;
property tp:TVector2 read GetTP write SetTP;
property tpp:TVector3 read GetTPP;
property tps:TVector3 read GetTPS write SetTPS;
property tpt:TVector3 read GetTPT;
property ts:TVector2 read GetTS write SetTS;
property tsp:TVector3 read GetTSP write SetTSP;
property tss:TVector3 read GetTSS;
property tst:TVector3 read GetTST;
property tt:TVector2 read GetTT;
property ttp:TVector3 read GetTTP;
property tts:TVector3 read GetTTS;
property ttt:TVector3 read GetTTT;
property xx:TVector2 read GetXX;
property xxx:TVector3 read GetXXX;
property xxy:TVector3 read GetXXY;
property xxz:TVector3 read GetXXZ;
property xy:TVector2 read GetXY write SetXY;
property xyx:TVector3 read GetXYX;
property xyy:TVector3 read GetXYY;
property xyz:TVector3 read GetXYZ write SetXYZ;
property xz:TVector2 read GetXZ write SetXZ;
property xzx:TVector3 read GetXZX;
property xzy:TVector3 read GetXZY write SetXZY;
property xzz:TVector3 read GetXZZ;
property yx:TVector2 read GetYX write SetYX;
property yxx:TVector3 read GetYXX;
property yxy:TVector3 read GetYXY;
property yxz:TVector3 read GetYXZ write SetYXZ;
property yy:TVector2 read GetYY;
property yyx:TVector3 read GetYYX;
property yyy:TVector3 read GetYYY;
property yyz:TVector3 read GetYYZ;
property yz:TVector2 read GetYZ write SetYZ;
property yzx:TVector3 read GetYZX write SetYZX;
property yzy:TVector3 read GetYZY;
property yzz:TVector3 read GetYZZ;
property zx:TVector2 read GetZX write SetZX;
property zxx:TVector3 read GetZXX;
property zxy:TVector3 read GetZXY write SetZXY;
property zxz:TVector3 read GetZXZ;
property zy:TVector2 read GetZY write SetZY;
property zyx:TVector3 read GetZYX write SetZYX;
property zyy:TVector3 read GetZYY;
property zyz:TVector3 read GetZYZ;
property zz:TVector2 read GetZZ;
property zzx:TVector3 read GetZZX;
property zzy:TVector3 read GetZZY;
property zzz:TVector3 read GetZZZ;
