function TVector3Helper.GetXXXX:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=x;
 result.w:=x;
end;
function TVector3Helper.GetXXXY:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=x;
 result.w:=y;
end;
function TVector3Helper.GetXXXZ:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=x;
 result.w:=z;
end;
function TVector3Helper.GetXXYX:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=y;
 result.w:=x;
end;
function TVector3Helper.GetXXYY:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=y;
 result.w:=y;
end;
function TVector3Helper.GetXXYZ:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=y;
 result.w:=z;
end;
function TVector3Helper.GetXXZX:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=z;
 result.w:=x;
end;
function TVector3Helper.GetXXZY:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=z;
 result.w:=y;
end;
function TVector3Helper.GetXXZZ:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=z;
 result.w:=z;
end;
function TVector3Helper.GetXYXX:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=x;
 result.w:=x;
end;
function TVector3Helper.GetXYXY:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=x;
 result.w:=y;
end;
function TVector3Helper.GetXYXZ:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=x;
 result.w:=z;
end;
function TVector3Helper.GetXYYX:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=y;
 result.w:=x;
end;
function TVector3Helper.GetXYYY:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=y;
 result.w:=y;
end;
function TVector3Helper.GetXYYZ:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=y;
 result.w:=z;
end;
function TVector3Helper.GetXYZX:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=z;
 result.w:=x;
end;
function TVector3Helper.GetXYZY:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=z;
 result.w:=y;
end;
function TVector3Helper.GetXYZZ:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=z;
 result.w:=z;
end;
function TVector3Helper.GetXZXX:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=x;
 result.w:=x;
end;
function TVector3Helper.GetXZXY:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=x;
 result.w:=y;
end;
function TVector3Helper.GetXZXZ:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=x;
 result.w:=z;
end;
function TVector3Helper.GetXZYX:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=y;
 result.w:=x;
end;
function TVector3Helper.GetXZYY:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=y;
 result.w:=y;
end;
function TVector3Helper.GetXZYZ:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=y;
 result.w:=z;
end;
function TVector3Helper.GetXZZX:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=z;
 result.w:=x;
end;
function TVector3Helper.GetXZZY:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=z;
 result.w:=y;
end;
function TVector3Helper.GetXZZZ:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=z;
 result.w:=z;
end;
function TVector3Helper.GetYXXX:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=x;
 result.w:=x;
end;
function TVector3Helper.GetYXXY:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=x;
 result.w:=y;
end;
function TVector3Helper.GetYXXZ:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=x;
 result.w:=z;
end;
function TVector3Helper.GetYXYX:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=y;
 result.w:=x;
end;
function TVector3Helper.GetYXYY:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=y;
 result.w:=y;
end;
function TVector3Helper.GetYXYZ:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=y;
 result.w:=z;
end;
function TVector3Helper.GetYXZX:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=z;
 result.w:=x;
end;
function TVector3Helper.GetYXZY:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=z;
 result.w:=y;
end;
function TVector3Helper.GetYXZZ:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=z;
 result.w:=z;
end;
function TVector3Helper.GetYYXX:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=x;
 result.w:=x;
end;
function TVector3Helper.GetYYXY:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=x;
 result.w:=y;
end;
function TVector3Helper.GetYYXZ:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=x;
 result.w:=z;
end;
function TVector3Helper.GetYYYX:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=y;
 result.w:=x;
end;
function TVector3Helper.GetYYYY:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=y;
 result.w:=y;
end;
function TVector3Helper.GetYYYZ:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=y;
 result.w:=z;
end;
function TVector3Helper.GetYYZX:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=z;
 result.w:=x;
end;
function TVector3Helper.GetYYZY:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=z;
 result.w:=y;
end;
function TVector3Helper.GetYYZZ:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=z;
 result.w:=z;
end;
function TVector3Helper.GetYZXX:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=x;
 result.w:=x;
end;
function TVector3Helper.GetYZXY:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=x;
 result.w:=y;
end;
function TVector3Helper.GetYZXZ:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=x;
 result.w:=z;
end;
function TVector3Helper.GetYZYX:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=y;
 result.w:=x;
end;
function TVector3Helper.GetYZYY:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=y;
 result.w:=y;
end;
function TVector3Helper.GetYZYZ:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=y;
 result.w:=z;
end;
function TVector3Helper.GetYZZX:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=z;
 result.w:=x;
end;
function TVector3Helper.GetYZZY:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=z;
 result.w:=y;
end;
function TVector3Helper.GetYZZZ:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=z;
 result.w:=z;
end;
function TVector3Helper.GetZXXX:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=x;
 result.w:=x;
end;
function TVector3Helper.GetZXXY:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=x;
 result.w:=y;
end;
function TVector3Helper.GetZXXZ:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=x;
 result.w:=z;
end;
function TVector3Helper.GetZXYX:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=y;
 result.w:=x;
end;
function TVector3Helper.GetZXYY:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=y;
 result.w:=y;
end;
function TVector3Helper.GetZXYZ:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=y;
 result.w:=z;
end;
function TVector3Helper.GetZXZX:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=z;
 result.w:=x;
end;
function TVector3Helper.GetZXZY:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=z;
 result.w:=y;
end;
function TVector3Helper.GetZXZZ:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=z;
 result.w:=z;
end;
function TVector3Helper.GetZYXX:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=x;
 result.w:=x;
end;
function TVector3Helper.GetZYXY:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=x;
 result.w:=y;
end;
function TVector3Helper.GetZYXZ:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=x;
 result.w:=z;
end;
function TVector3Helper.GetZYYX:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=y;
 result.w:=x;
end;
function TVector3Helper.GetZYYY:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=y;
 result.w:=y;
end;
function TVector3Helper.GetZYYZ:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=y;
 result.w:=z;
end;
function TVector3Helper.GetZYZX:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=z;
 result.w:=x;
end;
function TVector3Helper.GetZYZY:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=z;
 result.w:=y;
end;
function TVector3Helper.GetZYZZ:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=z;
 result.w:=z;
end;
function TVector3Helper.GetZZXX:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=x;
 result.w:=x;
end;
function TVector3Helper.GetZZXY:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=x;
 result.w:=y;
end;
function TVector3Helper.GetZZXZ:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=x;
 result.w:=z;
end;
function TVector3Helper.GetZZYX:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=y;
 result.w:=x;
end;
function TVector3Helper.GetZZYY:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=y;
 result.w:=y;
end;
function TVector3Helper.GetZZYZ:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=y;
 result.w:=z;
end;
function TVector3Helper.GetZZZX:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=z;
 result.w:=x;
end;
function TVector3Helper.GetZZZY:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=z;
 result.w:=y;
end;
function TVector3Helper.GetZZZZ:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=z;
 result.w:=z;
end;
function TVector3Helper.GetRRRR:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=r;
 result.a:=r;
end;
function TVector3Helper.GetRRRG:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=r;
 result.a:=g;
end;
function TVector3Helper.GetRRRB:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=r;
 result.a:=b;
end;
function TVector3Helper.GetRRGR:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=g;
 result.a:=r;
end;
function TVector3Helper.GetRRGG:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=g;
 result.a:=g;
end;
function TVector3Helper.GetRRGB:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=g;
 result.a:=b;
end;
function TVector3Helper.GetRRBR:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=b;
 result.a:=r;
end;
function TVector3Helper.GetRRBG:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=b;
 result.a:=g;
end;
function TVector3Helper.GetRRBB:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=b;
 result.a:=b;
end;
function TVector3Helper.GetRGRR:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=r;
 result.a:=r;
end;
function TVector3Helper.GetRGRG:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=r;
 result.a:=g;
end;
function TVector3Helper.GetRGRB:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=r;
 result.a:=b;
end;
function TVector3Helper.GetRGGR:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=g;
 result.a:=r;
end;
function TVector3Helper.GetRGGG:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=g;
 result.a:=g;
end;
function TVector3Helper.GetRGGB:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=g;
 result.a:=b;
end;
function TVector3Helper.GetRGBR:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=b;
 result.a:=r;
end;
function TVector3Helper.GetRGBG:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=b;
 result.a:=g;
end;
function TVector3Helper.GetRGBB:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=b;
 result.a:=b;
end;
function TVector3Helper.GetRBRR:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=r;
 result.a:=r;
end;
function TVector3Helper.GetRBRG:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=r;
 result.a:=g;
end;
function TVector3Helper.GetRBRB:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=r;
 result.a:=b;
end;
function TVector3Helper.GetRBGR:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=g;
 result.a:=r;
end;
function TVector3Helper.GetRBGG:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=g;
 result.a:=g;
end;
function TVector3Helper.GetRBGB:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=g;
 result.a:=b;
end;
function TVector3Helper.GetRBBR:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=b;
 result.a:=r;
end;
function TVector3Helper.GetRBBG:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=b;
 result.a:=g;
end;
function TVector3Helper.GetRBBB:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=b;
 result.a:=b;
end;
function TVector3Helper.GetGRRR:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=r;
 result.a:=r;
end;
function TVector3Helper.GetGRRG:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=r;
 result.a:=g;
end;
function TVector3Helper.GetGRRB:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=r;
 result.a:=b;
end;
function TVector3Helper.GetGRGR:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=g;
 result.a:=r;
end;
function TVector3Helper.GetGRGG:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=g;
 result.a:=g;
end;
function TVector3Helper.GetGRGB:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=g;
 result.a:=b;
end;
function TVector3Helper.GetGRBR:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=b;
 result.a:=r;
end;
function TVector3Helper.GetGRBG:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=b;
 result.a:=g;
end;
function TVector3Helper.GetGRBB:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=b;
 result.a:=b;
end;
function TVector3Helper.GetGGRR:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=r;
 result.a:=r;
end;
function TVector3Helper.GetGGRG:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=r;
 result.a:=g;
end;
function TVector3Helper.GetGGRB:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=r;
 result.a:=b;
end;
function TVector3Helper.GetGGGR:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=g;
 result.a:=r;
end;
function TVector3Helper.GetGGGG:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=g;
 result.a:=g;
end;
function TVector3Helper.GetGGGB:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=g;
 result.a:=b;
end;
function TVector3Helper.GetGGBR:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=b;
 result.a:=r;
end;
function TVector3Helper.GetGGBG:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=b;
 result.a:=g;
end;
function TVector3Helper.GetGGBB:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=b;
 result.a:=b;
end;
function TVector3Helper.GetGBRR:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=r;
 result.a:=r;
end;
function TVector3Helper.GetGBRG:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=r;
 result.a:=g;
end;
function TVector3Helper.GetGBRB:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=r;
 result.a:=b;
end;
function TVector3Helper.GetGBGR:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=g;
 result.a:=r;
end;
function TVector3Helper.GetGBGG:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=g;
 result.a:=g;
end;
function TVector3Helper.GetGBGB:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=g;
 result.a:=b;
end;
function TVector3Helper.GetGBBR:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=b;
 result.a:=r;
end;
function TVector3Helper.GetGBBG:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=b;
 result.a:=g;
end;
function TVector3Helper.GetGBBB:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=b;
 result.a:=b;
end;
function TVector3Helper.GetBRRR:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=r;
 result.a:=r;
end;
function TVector3Helper.GetBRRG:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=r;
 result.a:=g;
end;
function TVector3Helper.GetBRRB:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=r;
 result.a:=b;
end;
function TVector3Helper.GetBRGR:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=g;
 result.a:=r;
end;
function TVector3Helper.GetBRGG:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=g;
 result.a:=g;
end;
function TVector3Helper.GetBRGB:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=g;
 result.a:=b;
end;
function TVector3Helper.GetBRBR:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=b;
 result.a:=r;
end;
function TVector3Helper.GetBRBG:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=b;
 result.a:=g;
end;
function TVector3Helper.GetBRBB:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=b;
 result.a:=b;
end;
function TVector3Helper.GetBGRR:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=r;
 result.a:=r;
end;
function TVector3Helper.GetBGRG:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=r;
 result.a:=g;
end;
function TVector3Helper.GetBGRB:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=r;
 result.a:=b;
end;
function TVector3Helper.GetBGGR:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=g;
 result.a:=r;
end;
function TVector3Helper.GetBGGG:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=g;
 result.a:=g;
end;
function TVector3Helper.GetBGGB:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=g;
 result.a:=b;
end;
function TVector3Helper.GetBGBR:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=b;
 result.a:=r;
end;
function TVector3Helper.GetBGBG:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=b;
 result.a:=g;
end;
function TVector3Helper.GetBGBB:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=b;
 result.a:=b;
end;
function TVector3Helper.GetBBRR:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=r;
 result.a:=r;
end;
function TVector3Helper.GetBBRG:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=r;
 result.a:=g;
end;
function TVector3Helper.GetBBRB:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=r;
 result.a:=b;
end;
function TVector3Helper.GetBBGR:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=g;
 result.a:=r;
end;
function TVector3Helper.GetBBGG:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=g;
 result.a:=g;
end;
function TVector3Helper.GetBBGB:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=g;
 result.a:=b;
end;
function TVector3Helper.GetBBBR:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=b;
 result.a:=r;
end;
function TVector3Helper.GetBBBG:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=b;
 result.a:=g;
end;
function TVector3Helper.GetBBBB:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=b;
 result.a:=b;
end;
function TVector3Helper.GetSSSS:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=s;
 result.q:=s;
end;
function TVector3Helper.GetSSST:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=s;
 result.q:=t;
end;
function TVector3Helper.GetSSSP:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=s;
 result.q:=p;
end;
function TVector3Helper.GetSSTS:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=t;
 result.q:=s;
end;
function TVector3Helper.GetSSTT:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=t;
 result.q:=t;
end;
function TVector3Helper.GetSSTP:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=t;
 result.q:=p;
end;
function TVector3Helper.GetSSPS:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=p;
 result.q:=s;
end;
function TVector3Helper.GetSSPT:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=p;
 result.q:=t;
end;
function TVector3Helper.GetSSPP:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=p;
 result.q:=p;
end;
function TVector3Helper.GetSTSS:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=s;
 result.q:=s;
end;
function TVector3Helper.GetSTST:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=s;
 result.q:=t;
end;
function TVector3Helper.GetSTSP:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=s;
 result.q:=p;
end;
function TVector3Helper.GetSTTS:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=t;
 result.q:=s;
end;
function TVector3Helper.GetSTTT:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=t;
 result.q:=t;
end;
function TVector3Helper.GetSTTP:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=t;
 result.q:=p;
end;
function TVector3Helper.GetSTPS:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=p;
 result.q:=s;
end;
function TVector3Helper.GetSTPT:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=p;
 result.q:=t;
end;
function TVector3Helper.GetSTPP:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=p;
 result.q:=p;
end;
function TVector3Helper.GetSPSS:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=s;
 result.q:=s;
end;
function TVector3Helper.GetSPST:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=s;
 result.q:=t;
end;
function TVector3Helper.GetSPSP:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=s;
 result.q:=p;
end;
function TVector3Helper.GetSPTS:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=t;
 result.q:=s;
end;
function TVector3Helper.GetSPTT:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=t;
 result.q:=t;
end;
function TVector3Helper.GetSPTP:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=t;
 result.q:=p;
end;
function TVector3Helper.GetSPPS:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=p;
 result.q:=s;
end;
function TVector3Helper.GetSPPT:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=p;
 result.q:=t;
end;
function TVector3Helper.GetSPPP:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=p;
 result.q:=p;
end;
function TVector3Helper.GetTSSS:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=s;
 result.q:=s;
end;
function TVector3Helper.GetTSST:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=s;
 result.q:=t;
end;
function TVector3Helper.GetTSSP:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=s;
 result.q:=p;
end;
function TVector3Helper.GetTSTS:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=t;
 result.q:=s;
end;
function TVector3Helper.GetTSTT:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=t;
 result.q:=t;
end;
function TVector3Helper.GetTSTP:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=t;
 result.q:=p;
end;
function TVector3Helper.GetTSPS:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=p;
 result.q:=s;
end;
function TVector3Helper.GetTSPT:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=p;
 result.q:=t;
end;
function TVector3Helper.GetTSPP:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=p;
 result.q:=p;
end;
function TVector3Helper.GetTTSS:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=s;
 result.q:=s;
end;
function TVector3Helper.GetTTST:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=s;
 result.q:=t;
end;
function TVector3Helper.GetTTSP:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=s;
 result.q:=p;
end;
function TVector3Helper.GetTTTS:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=t;
 result.q:=s;
end;
function TVector3Helper.GetTTTT:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=t;
 result.q:=t;
end;
function TVector3Helper.GetTTTP:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=t;
 result.q:=p;
end;
function TVector3Helper.GetTTPS:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=p;
 result.q:=s;
end;
function TVector3Helper.GetTTPT:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=p;
 result.q:=t;
end;
function TVector3Helper.GetTTPP:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=p;
 result.q:=p;
end;
function TVector3Helper.GetTPSS:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=s;
 result.q:=s;
end;
function TVector3Helper.GetTPST:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=s;
 result.q:=t;
end;
function TVector3Helper.GetTPSP:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=s;
 result.q:=p;
end;
function TVector3Helper.GetTPTS:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=t;
 result.q:=s;
end;
function TVector3Helper.GetTPTT:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=t;
 result.q:=t;
end;
function TVector3Helper.GetTPTP:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=t;
 result.q:=p;
end;
function TVector3Helper.GetTPPS:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=p;
 result.q:=s;
end;
function TVector3Helper.GetTPPT:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=p;
 result.q:=t;
end;
function TVector3Helper.GetTPPP:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=p;
 result.q:=p;
end;
function TVector3Helper.GetPSSS:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=s;
 result.q:=s;
end;
function TVector3Helper.GetPSST:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=s;
 result.q:=t;
end;
function TVector3Helper.GetPSSP:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=s;
 result.q:=p;
end;
function TVector3Helper.GetPSTS:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=t;
 result.q:=s;
end;
function TVector3Helper.GetPSTT:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=t;
 result.q:=t;
end;
function TVector3Helper.GetPSTP:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=t;
 result.q:=p;
end;
function TVector3Helper.GetPSPS:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=p;
 result.q:=s;
end;
function TVector3Helper.GetPSPT:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=p;
 result.q:=t;
end;
function TVector3Helper.GetPSPP:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=p;
 result.q:=p;
end;
function TVector3Helper.GetPTSS:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=s;
 result.q:=s;
end;
function TVector3Helper.GetPTST:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=s;
 result.q:=t;
end;
function TVector3Helper.GetPTSP:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=s;
 result.q:=p;
end;
function TVector3Helper.GetPTTS:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=t;
 result.q:=s;
end;
function TVector3Helper.GetPTTT:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=t;
 result.q:=t;
end;
function TVector3Helper.GetPTTP:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=t;
 result.q:=p;
end;
function TVector3Helper.GetPTPS:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=p;
 result.q:=s;
end;
function TVector3Helper.GetPTPT:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=p;
 result.q:=t;
end;
function TVector3Helper.GetPTPP:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=p;
 result.q:=p;
end;
function TVector3Helper.GetPPSS:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=s;
 result.q:=s;
end;
function TVector3Helper.GetPPST:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=s;
 result.q:=t;
end;
function TVector3Helper.GetPPSP:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=s;
 result.q:=p;
end;
function TVector3Helper.GetPPTS:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=t;
 result.q:=s;
end;
function TVector3Helper.GetPPTT:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=t;
 result.q:=t;
end;
function TVector3Helper.GetPPTP:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=t;
 result.q:=p;
end;
function TVector3Helper.GetPPPS:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=p;
 result.q:=s;
end;
function TVector3Helper.GetPPPT:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=p;
 result.q:=t;
end;
function TVector3Helper.GetPPPP:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=p;
 result.q:=p;
end;
