function TVector2Helper.GetXXX:TVector3;
begin
 result.x:=x;
 result.y:=x;
 result.z:=x;
end;
function TVector2Helper.GetXXXX:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=x;
 result.w:=x;
end;
function TVector2Helper.GetXXXY:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=x;
 result.w:=y;
end;
function TVector2Helper.GetXXY:TVector3;
begin
 result.x:=x;
 result.y:=x;
 result.z:=y;
end;
function TVector2Helper.GetXXYX:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=y;
 result.w:=x;
end;
function TVector2Helper.GetXXYY:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=y;
 result.w:=y;
end;
function TVector2Helper.GetXYX:TVector3;
begin
 result.x:=x;
 result.y:=y;
 result.z:=x;
end;
function TVector2Helper.GetXYXX:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=x;
 result.w:=x;
end;
function TVector2Helper.GetXYXY:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=x;
 result.w:=y;
end;
function TVector2Helper.GetXYY:TVector3;
begin
 result.x:=x;
 result.y:=y;
 result.z:=y;
end;
function TVector2Helper.GetXYYX:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=y;
 result.w:=x;
end;
function TVector2Helper.GetXYYY:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=y;
 result.w:=y;
end;
function TVector2Helper.GetYXX:TVector3;
begin
 result.x:=y;
 result.y:=x;
 result.z:=x;
end;
function TVector2Helper.GetYXXX:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=x;
 result.w:=x;
end;
function TVector2Helper.GetYXXY:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=x;
 result.w:=y;
end;
function TVector2Helper.GetYXY:TVector3;
begin
 result.x:=y;
 result.y:=x;
 result.z:=y;
end;
function TVector2Helper.GetYXYX:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=y;
 result.w:=x;
end;
function TVector2Helper.GetYXYY:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=y;
 result.w:=y;
end;
function TVector2Helper.GetYYX:TVector3;
begin
 result.x:=y;
 result.y:=y;
 result.z:=x;
end;
function TVector2Helper.GetYYXX:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=x;
 result.w:=x;
end;
function TVector2Helper.GetYYXY:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=x;
 result.w:=y;
end;
function TVector2Helper.GetYYY:TVector3;
begin
 result.x:=y;
 result.y:=y;
 result.z:=y;
end;
function TVector2Helper.GetYYYX:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=y;
 result.w:=x;
end;
function TVector2Helper.GetYYYY:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=y;
 result.w:=y;
end;
function TVector2Helper.GetRRR:TVector3;
begin
 result.r:=r;
 result.g:=r;
 result.b:=r;
end;
function TVector2Helper.GetRRRR:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=r;
 result.a:=r;
end;
function TVector2Helper.GetRRRG:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=r;
 result.a:=g;
end;
function TVector2Helper.GetRRG:TVector3;
begin
 result.r:=r;
 result.g:=r;
 result.b:=g;
end;
function TVector2Helper.GetRRGR:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=g;
 result.a:=r;
end;
function TVector2Helper.GetRRGG:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=g;
 result.a:=g;
end;
function TVector2Helper.GetRGR:TVector3;
begin
 result.r:=r;
 result.g:=g;
 result.b:=r;
end;
function TVector2Helper.GetRGRR:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=r;
 result.a:=r;
end;
function TVector2Helper.GetRGRG:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=r;
 result.a:=g;
end;
function TVector2Helper.GetRGG:TVector3;
begin
 result.r:=r;
 result.g:=g;
 result.b:=g;
end;
function TVector2Helper.GetRGGR:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=g;
 result.a:=r;
end;
function TVector2Helper.GetRGGG:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=g;
 result.a:=g;
end;
function TVector2Helper.GetGRR:TVector3;
begin
 result.r:=g;
 result.g:=r;
 result.b:=r;
end;
function TVector2Helper.GetGRRR:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=r;
 result.a:=r;
end;
function TVector2Helper.GetGRRG:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=r;
 result.a:=g;
end;
function TVector2Helper.GetGRG:TVector3;
begin
 result.r:=g;
 result.g:=r;
 result.b:=g;
end;
function TVector2Helper.GetGRGR:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=g;
 result.a:=r;
end;
function TVector2Helper.GetGRGG:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=g;
 result.a:=g;
end;
function TVector2Helper.GetGGR:TVector3;
begin
 result.r:=g;
 result.g:=g;
 result.b:=r;
end;
function TVector2Helper.GetGGRR:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=r;
 result.a:=r;
end;
function TVector2Helper.GetGGRG:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=r;
 result.a:=g;
end;
function TVector2Helper.GetGGG:TVector3;
begin
 result.r:=g;
 result.g:=g;
 result.b:=g;
end;
function TVector2Helper.GetGGGR:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=g;
 result.a:=r;
end;
function TVector2Helper.GetGGGG:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=g;
 result.a:=g;
end;
function TVector2Helper.GetSSS:TVector3;
begin
 result.s:=s;
 result.t:=s;
 result.p:=s;
end;
function TVector2Helper.GetSSSS:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=s;
 result.q:=s;
end;
function TVector2Helper.GetSSST:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=s;
 result.q:=t;
end;
function TVector2Helper.GetSST:TVector3;
begin
 result.s:=s;
 result.t:=s;
 result.p:=t;
end;
function TVector2Helper.GetSSTS:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=t;
 result.q:=s;
end;
function TVector2Helper.GetSSTT:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=t;
 result.q:=t;
end;
function TVector2Helper.GetSTS:TVector3;
begin
 result.s:=s;
 result.t:=t;
 result.p:=s;
end;
function TVector2Helper.GetSTSS:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=s;
 result.q:=s;
end;
function TVector2Helper.GetSTST:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=s;
 result.q:=t;
end;
function TVector2Helper.GetSTT:TVector3;
begin
 result.s:=s;
 result.t:=t;
 result.p:=t;
end;
function TVector2Helper.GetSTTS:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=t;
 result.q:=s;
end;
function TVector2Helper.GetSTTT:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=t;
 result.q:=t;
end;
function TVector2Helper.GetTSS:TVector3;
begin
 result.s:=t;
 result.t:=s;
 result.p:=s;
end;
function TVector2Helper.GetTSSS:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=s;
 result.q:=s;
end;
function TVector2Helper.GetTSST:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=s;
 result.q:=t;
end;
function TVector2Helper.GetTST:TVector3;
begin
 result.s:=t;
 result.t:=s;
 result.p:=t;
end;
function TVector2Helper.GetTSTS:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=t;
 result.q:=s;
end;
function TVector2Helper.GetTSTT:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=t;
 result.q:=t;
end;
function TVector2Helper.GetTTS:TVector3;
begin
 result.s:=t;
 result.t:=t;
 result.p:=s;
end;
function TVector2Helper.GetTTSS:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=s;
 result.q:=s;
end;
function TVector2Helper.GetTTST:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=s;
 result.q:=t;
end;
function TVector2Helper.GetTTT:TVector3;
begin
 result.s:=t;
 result.t:=t;
 result.p:=t;
end;
function TVector2Helper.GetTTTS:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=t;
 result.q:=s;
end;
function TVector2Helper.GetTTTT:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=t;
 result.q:=t;
end;
