function TVector4.GetXX:TVector2;
begin
 result.x:=x;
 result.y:=x;
end;
function TVector4.GetXXX:TVector3;
begin
 result.x:=x;
 result.y:=x;
 result.z:=x;
end;
function TVector4.GetXXXX:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetXXXY:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetXXXZ:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetXXXW:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetXXY:TVector3;
begin
 result.x:=x;
 result.y:=x;
 result.z:=y;
end;
function TVector4.GetXXYX:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetXXYY:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetXXYZ:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetXXYW:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetXXZ:TVector3;
begin
 result.x:=x;
 result.y:=x;
 result.z:=z;
end;
function TVector4.GetXXZX:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetXXZY:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetXXZZ:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetXXZW:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetXXW:TVector3;
begin
 result.x:=x;
 result.y:=x;
 result.z:=w;
end;
function TVector4.GetXXWX:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetXXWY:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetXXWZ:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetXXWW:TVector4;
begin
 result.x:=x;
 result.y:=x;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetXY:TVector2;
begin
 result.x:=x;
 result.y:=y;
end;
procedure TVector4.SetXY(const pValue:TVector2);
begin
 x:=pValue.x;
 y:=pValue.y;
end;
function TVector4.GetXYX:TVector3;
begin
 result.x:=x;
 result.y:=y;
 result.z:=x;
end;
function TVector4.GetXYXX:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetXYXY:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetXYXZ:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetXYXW:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetXYY:TVector3;
begin
 result.x:=x;
 result.y:=y;
 result.z:=y;
end;
function TVector4.GetXYYX:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetXYYY:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetXYYZ:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetXYYW:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetXYZ:TVector3;
begin
 result.x:=x;
 result.y:=y;
 result.z:=z;
end;
procedure TVector4.SetXYZ(const pValue:TVector3);
begin
 x:=pValue.x;
 y:=pValue.y;
 z:=pValue.z;
end;
function TVector4.GetXYZX:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetXYZY:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetXYZZ:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetXYZW:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=z;
 result.w:=w;
end;
procedure TVector4.SetXYZW(const pValue:TVector4);
begin
 x:=pValue.x;
 y:=pValue.y;
 z:=pValue.z;
 w:=pValue.w;
end;
function TVector4.GetXYW:TVector3;
begin
 result.x:=x;
 result.y:=y;
 result.z:=w;
end;
procedure TVector4.SetXYW(const pValue:TVector3);
begin
 x:=pValue.x;
 y:=pValue.y;
 w:=pValue.z;
end;
function TVector4.GetXYWX:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetXYWY:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetXYWZ:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=w;
 result.w:=z;
end;
procedure TVector4.SetXYWZ(const pValue:TVector4);
begin
 x:=pValue.x;
 y:=pValue.y;
 w:=pValue.z;
 z:=pValue.w;
end;
function TVector4.GetXYWW:TVector4;
begin
 result.x:=x;
 result.y:=y;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetXZ:TVector2;
begin
 result.x:=x;
 result.y:=z;
end;
procedure TVector4.SetXZ(const pValue:TVector2);
begin
 x:=pValue.x;
 z:=pValue.y;
end;
function TVector4.GetXZX:TVector3;
begin
 result.x:=x;
 result.y:=z;
 result.z:=x;
end;
function TVector4.GetXZXX:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetXZXY:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetXZXZ:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetXZXW:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetXZY:TVector3;
begin
 result.x:=x;
 result.y:=z;
 result.z:=y;
end;
procedure TVector4.SetXZY(const pValue:TVector3);
begin
 x:=pValue.x;
 z:=pValue.y;
 y:=pValue.z;
end;
function TVector4.GetXZYX:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetXZYY:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetXZYZ:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetXZYW:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=y;
 result.w:=w;
end;
procedure TVector4.SetXZYW(const pValue:TVector4);
begin
 x:=pValue.x;
 z:=pValue.y;
 y:=pValue.z;
 w:=pValue.w;
end;
function TVector4.GetXZZ:TVector3;
begin
 result.x:=x;
 result.y:=z;
 result.z:=z;
end;
function TVector4.GetXZZX:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetXZZY:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetXZZZ:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetXZZW:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetXZW:TVector3;
begin
 result.x:=x;
 result.y:=z;
 result.z:=w;
end;
procedure TVector4.SetXZW(const pValue:TVector3);
begin
 x:=pValue.x;
 z:=pValue.y;
 w:=pValue.z;
end;
function TVector4.GetXZWX:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetXZWY:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=w;
 result.w:=y;
end;
procedure TVector4.SetXZWY(const pValue:TVector4);
begin
 x:=pValue.x;
 z:=pValue.y;
 w:=pValue.z;
 y:=pValue.w;
end;
function TVector4.GetXZWZ:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetXZWW:TVector4;
begin
 result.x:=x;
 result.y:=z;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetXW:TVector2;
begin
 result.x:=x;
 result.y:=w;
end;
procedure TVector4.SetXW(const pValue:TVector2);
begin
 x:=pValue.x;
 w:=pValue.y;
end;
function TVector4.GetXWX:TVector3;
begin
 result.x:=x;
 result.y:=w;
 result.z:=x;
end;
function TVector4.GetXWXX:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetXWXY:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetXWXZ:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetXWXW:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetXWY:TVector3;
begin
 result.x:=x;
 result.y:=w;
 result.z:=y;
end;
procedure TVector4.SetXWY(const pValue:TVector3);
begin
 x:=pValue.x;
 w:=pValue.y;
 y:=pValue.z;
end;
function TVector4.GetXWYX:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetXWYY:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetXWYZ:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=y;
 result.w:=z;
end;
procedure TVector4.SetXWYZ(const pValue:TVector4);
begin
 x:=pValue.x;
 w:=pValue.y;
 y:=pValue.z;
 z:=pValue.w;
end;
function TVector4.GetXWYW:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetXWZ:TVector3;
begin
 result.x:=x;
 result.y:=w;
 result.z:=z;
end;
procedure TVector4.SetXWZ(const pValue:TVector3);
begin
 x:=pValue.x;
 w:=pValue.y;
 z:=pValue.z;
end;
function TVector4.GetXWZX:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetXWZY:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=z;
 result.w:=y;
end;
procedure TVector4.SetXWZY(const pValue:TVector4);
begin
 x:=pValue.x;
 w:=pValue.y;
 z:=pValue.z;
 y:=pValue.w;
end;
function TVector4.GetXWZZ:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetXWZW:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetXWW:TVector3;
begin
 result.x:=x;
 result.y:=w;
 result.z:=w;
end;
function TVector4.GetXWWX:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetXWWY:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetXWWZ:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetXWWW:TVector4;
begin
 result.x:=x;
 result.y:=w;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetYX:TVector2;
begin
 result.x:=y;
 result.y:=x;
end;
procedure TVector4.SetYX(const pValue:TVector2);
begin
 y:=pValue.x;
 x:=pValue.y;
end;
function TVector4.GetYXX:TVector3;
begin
 result.x:=y;
 result.y:=x;
 result.z:=x;
end;
function TVector4.GetYXXX:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetYXXY:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetYXXZ:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetYXXW:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetYXY:TVector3;
begin
 result.x:=y;
 result.y:=x;
 result.z:=y;
end;
function TVector4.GetYXYX:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetYXYY:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetYXYZ:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetYXYW:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetYXZ:TVector3;
begin
 result.x:=y;
 result.y:=x;
 result.z:=z;
end;
procedure TVector4.SetYXZ(const pValue:TVector3);
begin
 y:=pValue.x;
 x:=pValue.y;
 z:=pValue.z;
end;
function TVector4.GetYXZX:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetYXZY:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetYXZZ:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetYXZW:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=z;
 result.w:=w;
end;
procedure TVector4.SetYXZW(const pValue:TVector4);
begin
 y:=pValue.x;
 x:=pValue.y;
 z:=pValue.z;
 w:=pValue.w;
end;
function TVector4.GetYXW:TVector3;
begin
 result.x:=y;
 result.y:=x;
 result.z:=w;
end;
procedure TVector4.SetYXW(const pValue:TVector3);
begin
 y:=pValue.x;
 x:=pValue.y;
 w:=pValue.z;
end;
function TVector4.GetYXWX:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetYXWY:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetYXWZ:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=w;
 result.w:=z;
end;
procedure TVector4.SetYXWZ(const pValue:TVector4);
begin
 y:=pValue.x;
 x:=pValue.y;
 w:=pValue.z;
 z:=pValue.w;
end;
function TVector4.GetYXWW:TVector4;
begin
 result.x:=y;
 result.y:=x;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetYY:TVector2;
begin
 result.x:=y;
 result.y:=y;
end;
function TVector4.GetYYX:TVector3;
begin
 result.x:=y;
 result.y:=y;
 result.z:=x;
end;
function TVector4.GetYYXX:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetYYXY:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetYYXZ:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetYYXW:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetYYY:TVector3;
begin
 result.x:=y;
 result.y:=y;
 result.z:=y;
end;
function TVector4.GetYYYX:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetYYYY:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetYYYZ:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetYYYW:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetYYZ:TVector3;
begin
 result.x:=y;
 result.y:=y;
 result.z:=z;
end;
function TVector4.GetYYZX:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetYYZY:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetYYZZ:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetYYZW:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetYYW:TVector3;
begin
 result.x:=y;
 result.y:=y;
 result.z:=w;
end;
function TVector4.GetYYWX:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetYYWY:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetYYWZ:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetYYWW:TVector4;
begin
 result.x:=y;
 result.y:=y;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetYZ:TVector2;
begin
 result.x:=y;
 result.y:=z;
end;
procedure TVector4.SetYZ(const pValue:TVector2);
begin
 y:=pValue.x;
 z:=pValue.y;
end;
function TVector4.GetYZX:TVector3;
begin
 result.x:=y;
 result.y:=z;
 result.z:=x;
end;
procedure TVector4.SetYZX(const pValue:TVector3);
begin
 y:=pValue.x;
 z:=pValue.y;
 x:=pValue.z;
end;
function TVector4.GetYZXX:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetYZXY:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetYZXZ:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetYZXW:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=x;
 result.w:=w;
end;
procedure TVector4.SetYZXW(const pValue:TVector4);
begin
 y:=pValue.x;
 z:=pValue.y;
 x:=pValue.z;
 w:=pValue.w;
end;
function TVector4.GetYZY:TVector3;
begin
 result.x:=y;
 result.y:=z;
 result.z:=y;
end;
function TVector4.GetYZYX:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetYZYY:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetYZYZ:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetYZYW:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetYZZ:TVector3;
begin
 result.x:=y;
 result.y:=z;
 result.z:=z;
end;
function TVector4.GetYZZX:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetYZZY:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetYZZZ:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetYZZW:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetYZW:TVector3;
begin
 result.x:=y;
 result.y:=z;
 result.z:=w;
end;
procedure TVector4.SetYZW(const pValue:TVector3);
begin
 y:=pValue.x;
 z:=pValue.y;
 w:=pValue.z;
end;
function TVector4.GetYZWX:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=w;
 result.w:=x;
end;
procedure TVector4.SetYZWX(const pValue:TVector4);
begin
 y:=pValue.x;
 z:=pValue.y;
 w:=pValue.z;
 x:=pValue.w;
end;
function TVector4.GetYZWY:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetYZWZ:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetYZWW:TVector4;
begin
 result.x:=y;
 result.y:=z;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetYW:TVector2;
begin
 result.x:=y;
 result.y:=w;
end;
procedure TVector4.SetYW(const pValue:TVector2);
begin
 y:=pValue.x;
 w:=pValue.y;
end;
function TVector4.GetYWX:TVector3;
begin
 result.x:=y;
 result.y:=w;
 result.z:=x;
end;
procedure TVector4.SetYWX(const pValue:TVector3);
begin
 y:=pValue.x;
 w:=pValue.y;
 x:=pValue.z;
end;
function TVector4.GetYWXX:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetYWXY:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetYWXZ:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=x;
 result.w:=z;
end;
procedure TVector4.SetYWXZ(const pValue:TVector4);
begin
 y:=pValue.x;
 w:=pValue.y;
 x:=pValue.z;
 z:=pValue.w;
end;
function TVector4.GetYWXW:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetYWY:TVector3;
begin
 result.x:=y;
 result.y:=w;
 result.z:=y;
end;
function TVector4.GetYWYX:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetYWYY:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetYWYZ:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetYWYW:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetYWZ:TVector3;
begin
 result.x:=y;
 result.y:=w;
 result.z:=z;
end;
procedure TVector4.SetYWZ(const pValue:TVector3);
begin
 y:=pValue.x;
 w:=pValue.y;
 z:=pValue.z;
end;
function TVector4.GetYWZX:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=z;
 result.w:=x;
end;
procedure TVector4.SetYWZX(const pValue:TVector4);
begin
 y:=pValue.x;
 w:=pValue.y;
 z:=pValue.z;
 x:=pValue.w;
end;
function TVector4.GetYWZY:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetYWZZ:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetYWZW:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetYWW:TVector3;
begin
 result.x:=y;
 result.y:=w;
 result.z:=w;
end;
function TVector4.GetYWWX:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetYWWY:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetYWWZ:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetYWWW:TVector4;
begin
 result.x:=y;
 result.y:=w;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetZX:TVector2;
begin
 result.x:=z;
 result.y:=x;
end;
procedure TVector4.SetZX(const pValue:TVector2);
begin
 z:=pValue.x;
 x:=pValue.y;
end;
function TVector4.GetZXX:TVector3;
begin
 result.x:=z;
 result.y:=x;
 result.z:=x;
end;
function TVector4.GetZXXX:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetZXXY:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetZXXZ:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetZXXW:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetZXY:TVector3;
begin
 result.x:=z;
 result.y:=x;
 result.z:=y;
end;
procedure TVector4.SetZXY(const pValue:TVector3);
begin
 z:=pValue.x;
 x:=pValue.y;
 y:=pValue.z;
end;
function TVector4.GetZXYX:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetZXYY:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetZXYZ:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetZXYW:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=y;
 result.w:=w;
end;
procedure TVector4.SetZXYW(const pValue:TVector4);
begin
 z:=pValue.x;
 x:=pValue.y;
 y:=pValue.z;
 w:=pValue.w;
end;
function TVector4.GetZXZ:TVector3;
begin
 result.x:=z;
 result.y:=x;
 result.z:=z;
end;
function TVector4.GetZXZX:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetZXZY:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetZXZZ:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetZXZW:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetZXW:TVector3;
begin
 result.x:=z;
 result.y:=x;
 result.z:=w;
end;
procedure TVector4.SetZXW(const pValue:TVector3);
begin
 z:=pValue.x;
 x:=pValue.y;
 w:=pValue.z;
end;
function TVector4.GetZXWX:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetZXWY:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=w;
 result.w:=y;
end;
procedure TVector4.SetZXWY(const pValue:TVector4);
begin
 z:=pValue.x;
 x:=pValue.y;
 w:=pValue.z;
 y:=pValue.w;
end;
function TVector4.GetZXWZ:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetZXWW:TVector4;
begin
 result.x:=z;
 result.y:=x;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetZY:TVector2;
begin
 result.x:=z;
 result.y:=y;
end;
procedure TVector4.SetZY(const pValue:TVector2);
begin
 z:=pValue.x;
 y:=pValue.y;
end;
function TVector4.GetZYX:TVector3;
begin
 result.x:=z;
 result.y:=y;
 result.z:=x;
end;
procedure TVector4.SetZYX(const pValue:TVector3);
begin
 z:=pValue.x;
 y:=pValue.y;
 x:=pValue.z;
end;
function TVector4.GetZYXX:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetZYXY:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetZYXZ:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetZYXW:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=x;
 result.w:=w;
end;
procedure TVector4.SetZYXW(const pValue:TVector4);
begin
 z:=pValue.x;
 y:=pValue.y;
 x:=pValue.z;
 w:=pValue.w;
end;
function TVector4.GetZYY:TVector3;
begin
 result.x:=z;
 result.y:=y;
 result.z:=y;
end;
function TVector4.GetZYYX:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetZYYY:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetZYYZ:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetZYYW:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetZYZ:TVector3;
begin
 result.x:=z;
 result.y:=y;
 result.z:=z;
end;
function TVector4.GetZYZX:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetZYZY:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetZYZZ:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetZYZW:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetZYW:TVector3;
begin
 result.x:=z;
 result.y:=y;
 result.z:=w;
end;
procedure TVector4.SetZYW(const pValue:TVector3);
begin
 z:=pValue.x;
 y:=pValue.y;
 w:=pValue.z;
end;
function TVector4.GetZYWX:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=w;
 result.w:=x;
end;
procedure TVector4.SetZYWX(const pValue:TVector4);
begin
 z:=pValue.x;
 y:=pValue.y;
 w:=pValue.z;
 x:=pValue.w;
end;
function TVector4.GetZYWY:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetZYWZ:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetZYWW:TVector4;
begin
 result.x:=z;
 result.y:=y;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetZZ:TVector2;
begin
 result.x:=z;
 result.y:=z;
end;
function TVector4.GetZZX:TVector3;
begin
 result.x:=z;
 result.y:=z;
 result.z:=x;
end;
function TVector4.GetZZXX:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetZZXY:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetZZXZ:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetZZXW:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetZZY:TVector3;
begin
 result.x:=z;
 result.y:=z;
 result.z:=y;
end;
function TVector4.GetZZYX:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetZZYY:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetZZYZ:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetZZYW:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetZZZ:TVector3;
begin
 result.x:=z;
 result.y:=z;
 result.z:=z;
end;
function TVector4.GetZZZX:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetZZZY:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetZZZZ:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetZZZW:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetZZW:TVector3;
begin
 result.x:=z;
 result.y:=z;
 result.z:=w;
end;
function TVector4.GetZZWX:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetZZWY:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetZZWZ:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetZZWW:TVector4;
begin
 result.x:=z;
 result.y:=z;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetZW:TVector2;
begin
 result.x:=z;
 result.y:=w;
end;
procedure TVector4.SetZW(const pValue:TVector2);
begin
 z:=pValue.x;
 w:=pValue.y;
end;
function TVector4.GetZWX:TVector3;
begin
 result.x:=z;
 result.y:=w;
 result.z:=x;
end;
procedure TVector4.SetZWX(const pValue:TVector3);
begin
 z:=pValue.x;
 w:=pValue.y;
 x:=pValue.z;
end;
function TVector4.GetZWXX:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetZWXY:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=x;
 result.w:=y;
end;
procedure TVector4.SetZWXY(const pValue:TVector4);
begin
 z:=pValue.x;
 w:=pValue.y;
 x:=pValue.z;
 y:=pValue.w;
end;
function TVector4.GetZWXZ:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetZWXW:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetZWY:TVector3;
begin
 result.x:=z;
 result.y:=w;
 result.z:=y;
end;
procedure TVector4.SetZWY(const pValue:TVector3);
begin
 z:=pValue.x;
 w:=pValue.y;
 y:=pValue.z;
end;
function TVector4.GetZWYX:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=y;
 result.w:=x;
end;
procedure TVector4.SetZWYX(const pValue:TVector4);
begin
 z:=pValue.x;
 w:=pValue.y;
 y:=pValue.z;
 x:=pValue.w;
end;
function TVector4.GetZWYY:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetZWYZ:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetZWYW:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetZWZ:TVector3;
begin
 result.x:=z;
 result.y:=w;
 result.z:=z;
end;
function TVector4.GetZWZX:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetZWZY:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetZWZZ:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetZWZW:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetZWW:TVector3;
begin
 result.x:=z;
 result.y:=w;
 result.z:=w;
end;
function TVector4.GetZWWX:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetZWWY:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetZWWZ:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetZWWW:TVector4;
begin
 result.x:=z;
 result.y:=w;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetWX:TVector2;
begin
 result.x:=w;
 result.y:=x;
end;
procedure TVector4.SetWX(const pValue:TVector2);
begin
 w:=pValue.x;
 x:=pValue.y;
end;
function TVector4.GetWXX:TVector3;
begin
 result.x:=w;
 result.y:=x;
 result.z:=x;
end;
function TVector4.GetWXXX:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetWXXY:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetWXXZ:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetWXXW:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetWXY:TVector3;
begin
 result.x:=w;
 result.y:=x;
 result.z:=y;
end;
procedure TVector4.SetWXY(const pValue:TVector3);
begin
 w:=pValue.x;
 x:=pValue.y;
 y:=pValue.z;
end;
function TVector4.GetWXYX:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetWXYY:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetWXYZ:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=y;
 result.w:=z;
end;
procedure TVector4.SetWXYZ(const pValue:TVector4);
begin
 w:=pValue.x;
 x:=pValue.y;
 y:=pValue.z;
 z:=pValue.w;
end;
function TVector4.GetWXYW:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetWXZ:TVector3;
begin
 result.x:=w;
 result.y:=x;
 result.z:=z;
end;
procedure TVector4.SetWXZ(const pValue:TVector3);
begin
 w:=pValue.x;
 x:=pValue.y;
 z:=pValue.z;
end;
function TVector4.GetWXZX:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetWXZY:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=z;
 result.w:=y;
end;
procedure TVector4.SetWXZY(const pValue:TVector4);
begin
 w:=pValue.x;
 x:=pValue.y;
 z:=pValue.z;
 y:=pValue.w;
end;
function TVector4.GetWXZZ:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetWXZW:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetWXW:TVector3;
begin
 result.x:=w;
 result.y:=x;
 result.z:=w;
end;
function TVector4.GetWXWX:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetWXWY:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetWXWZ:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetWXWW:TVector4;
begin
 result.x:=w;
 result.y:=x;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetWY:TVector2;
begin
 result.x:=w;
 result.y:=y;
end;
procedure TVector4.SetWY(const pValue:TVector2);
begin
 w:=pValue.x;
 y:=pValue.y;
end;
function TVector4.GetWYX:TVector3;
begin
 result.x:=w;
 result.y:=y;
 result.z:=x;
end;
procedure TVector4.SetWYX(const pValue:TVector3);
begin
 w:=pValue.x;
 y:=pValue.y;
 x:=pValue.z;
end;
function TVector4.GetWYXX:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetWYXY:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetWYXZ:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=x;
 result.w:=z;
end;
procedure TVector4.SetWYXZ(const pValue:TVector4);
begin
 w:=pValue.x;
 y:=pValue.y;
 x:=pValue.z;
 z:=pValue.w;
end;
function TVector4.GetWYXW:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetWYY:TVector3;
begin
 result.x:=w;
 result.y:=y;
 result.z:=y;
end;
function TVector4.GetWYYX:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetWYYY:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetWYYZ:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetWYYW:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetWYZ:TVector3;
begin
 result.x:=w;
 result.y:=y;
 result.z:=z;
end;
procedure TVector4.SetWYZ(const pValue:TVector3);
begin
 w:=pValue.x;
 y:=pValue.y;
 z:=pValue.z;
end;
function TVector4.GetWYZX:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=z;
 result.w:=x;
end;
procedure TVector4.SetWYZX(const pValue:TVector4);
begin
 w:=pValue.x;
 y:=pValue.y;
 z:=pValue.z;
 x:=pValue.w;
end;
function TVector4.GetWYZY:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetWYZZ:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetWYZW:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetWYW:TVector3;
begin
 result.x:=w;
 result.y:=y;
 result.z:=w;
end;
function TVector4.GetWYWX:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetWYWY:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetWYWZ:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetWYWW:TVector4;
begin
 result.x:=w;
 result.y:=y;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetWZ:TVector2;
begin
 result.x:=w;
 result.y:=z;
end;
procedure TVector4.SetWZ(const pValue:TVector2);
begin
 w:=pValue.x;
 z:=pValue.y;
end;
function TVector4.GetWZX:TVector3;
begin
 result.x:=w;
 result.y:=z;
 result.z:=x;
end;
procedure TVector4.SetWZX(const pValue:TVector3);
begin
 w:=pValue.x;
 z:=pValue.y;
 x:=pValue.z;
end;
function TVector4.GetWZXX:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetWZXY:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=x;
 result.w:=y;
end;
procedure TVector4.SetWZXY(const pValue:TVector4);
begin
 w:=pValue.x;
 z:=pValue.y;
 x:=pValue.z;
 y:=pValue.w;
end;
function TVector4.GetWZXZ:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetWZXW:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetWZY:TVector3;
begin
 result.x:=w;
 result.y:=z;
 result.z:=y;
end;
procedure TVector4.SetWZY(const pValue:TVector3);
begin
 w:=pValue.x;
 z:=pValue.y;
 y:=pValue.z;
end;
function TVector4.GetWZYX:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=y;
 result.w:=x;
end;
procedure TVector4.SetWZYX(const pValue:TVector4);
begin
 w:=pValue.x;
 z:=pValue.y;
 y:=pValue.z;
 x:=pValue.w;
end;
function TVector4.GetWZYY:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetWZYZ:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetWZYW:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetWZZ:TVector3;
begin
 result.x:=w;
 result.y:=z;
 result.z:=z;
end;
function TVector4.GetWZZX:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetWZZY:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetWZZZ:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetWZZW:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetWZW:TVector3;
begin
 result.x:=w;
 result.y:=z;
 result.z:=w;
end;
function TVector4.GetWZWX:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetWZWY:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetWZWZ:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetWZWW:TVector4;
begin
 result.x:=w;
 result.y:=z;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetWW:TVector2;
begin
 result.x:=w;
 result.y:=w;
end;
function TVector4.GetWWX:TVector3;
begin
 result.x:=w;
 result.y:=w;
 result.z:=x;
end;
function TVector4.GetWWXX:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=x;
 result.w:=x;
end;
function TVector4.GetWWXY:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=x;
 result.w:=y;
end;
function TVector4.GetWWXZ:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=x;
 result.w:=z;
end;
function TVector4.GetWWXW:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=x;
 result.w:=w;
end;
function TVector4.GetWWY:TVector3;
begin
 result.x:=w;
 result.y:=w;
 result.z:=y;
end;
function TVector4.GetWWYX:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=y;
 result.w:=x;
end;
function TVector4.GetWWYY:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=y;
 result.w:=y;
end;
function TVector4.GetWWYZ:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=y;
 result.w:=z;
end;
function TVector4.GetWWYW:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=y;
 result.w:=w;
end;
function TVector4.GetWWZ:TVector3;
begin
 result.x:=w;
 result.y:=w;
 result.z:=z;
end;
function TVector4.GetWWZX:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=z;
 result.w:=x;
end;
function TVector4.GetWWZY:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=z;
 result.w:=y;
end;
function TVector4.GetWWZZ:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=z;
 result.w:=z;
end;
function TVector4.GetWWZW:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=z;
 result.w:=w;
end;
function TVector4.GetWWW:TVector3;
begin
 result.x:=w;
 result.y:=w;
 result.z:=w;
end;
function TVector4.GetWWWX:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=w;
 result.w:=x;
end;
function TVector4.GetWWWY:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=w;
 result.w:=y;
end;
function TVector4.GetWWWZ:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=w;
 result.w:=z;
end;
function TVector4.GetWWWW:TVector4;
begin
 result.x:=w;
 result.y:=w;
 result.z:=w;
 result.w:=w;
end;
function TVector4.GetRR:TVector2;
begin
 result.r:=r;
 result.g:=r;
end;
function TVector4.GetRRR:TVector3;
begin
 result.r:=r;
 result.g:=r;
 result.b:=r;
end;
function TVector4.GetRRRR:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetRRRG:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetRRRB:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetRRRA:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetRRG:TVector3;
begin
 result.r:=r;
 result.g:=r;
 result.b:=g;
end;
function TVector4.GetRRGR:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetRRGG:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetRRGB:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetRRGA:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetRRB:TVector3;
begin
 result.r:=r;
 result.g:=r;
 result.b:=b;
end;
function TVector4.GetRRBR:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetRRBG:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetRRBB:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetRRBA:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetRRA:TVector3;
begin
 result.r:=r;
 result.g:=r;
 result.b:=a;
end;
function TVector4.GetRRAR:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetRRAG:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetRRAB:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetRRAA:TVector4;
begin
 result.r:=r;
 result.g:=r;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetRG:TVector2;
begin
 result.r:=r;
 result.g:=g;
end;
procedure TVector4.SetRG(const pValue:TVector2);
begin
 r:=pValue.r;
 g:=pValue.g;
end;
function TVector4.GetRGR:TVector3;
begin
 result.r:=r;
 result.g:=g;
 result.b:=r;
end;
function TVector4.GetRGRR:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetRGRG:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetRGRB:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetRGRA:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetRGG:TVector3;
begin
 result.r:=r;
 result.g:=g;
 result.b:=g;
end;
function TVector4.GetRGGR:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetRGGG:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetRGGB:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetRGGA:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetRGB:TVector3;
begin
 result.r:=r;
 result.g:=g;
 result.b:=b;
end;
procedure TVector4.SetRGB(const pValue:TVector3);
begin
 r:=pValue.r;
 g:=pValue.g;
 b:=pValue.b;
end;
function TVector4.GetRGBR:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetRGBG:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetRGBB:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetRGBA:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=b;
 result.a:=a;
end;
procedure TVector4.SetRGBA(const pValue:TVector4);
begin
 r:=pValue.r;
 g:=pValue.g;
 b:=pValue.b;
 a:=pValue.a;
end;
function TVector4.GetRGA:TVector3;
begin
 result.r:=r;
 result.g:=g;
 result.b:=a;
end;
procedure TVector4.SetRGA(const pValue:TVector3);
begin
 r:=pValue.r;
 g:=pValue.g;
 a:=pValue.b;
end;
function TVector4.GetRGAR:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetRGAG:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetRGAB:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=a;
 result.a:=b;
end;
procedure TVector4.SetRGAB(const pValue:TVector4);
begin
 r:=pValue.r;
 g:=pValue.g;
 a:=pValue.b;
 b:=pValue.a;
end;
function TVector4.GetRGAA:TVector4;
begin
 result.r:=r;
 result.g:=g;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetRB:TVector2;
begin
 result.r:=r;
 result.g:=b;
end;
procedure TVector4.SetRB(const pValue:TVector2);
begin
 r:=pValue.r;
 b:=pValue.g;
end;
function TVector4.GetRBR:TVector3;
begin
 result.r:=r;
 result.g:=b;
 result.b:=r;
end;
function TVector4.GetRBRR:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetRBRG:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetRBRB:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetRBRA:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetRBG:TVector3;
begin
 result.r:=r;
 result.g:=b;
 result.b:=g;
end;
procedure TVector4.SetRBG(const pValue:TVector3);
begin
 r:=pValue.r;
 b:=pValue.g;
 g:=pValue.b;
end;
function TVector4.GetRBGR:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetRBGG:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetRBGB:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetRBGA:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=g;
 result.a:=a;
end;
procedure TVector4.SetRBGA(const pValue:TVector4);
begin
 r:=pValue.r;
 b:=pValue.g;
 g:=pValue.b;
 a:=pValue.a;
end;
function TVector4.GetRBB:TVector3;
begin
 result.r:=r;
 result.g:=b;
 result.b:=b;
end;
function TVector4.GetRBBR:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetRBBG:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetRBBB:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetRBBA:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetRBA:TVector3;
begin
 result.r:=r;
 result.g:=b;
 result.b:=a;
end;
procedure TVector4.SetRBA(const pValue:TVector3);
begin
 r:=pValue.r;
 b:=pValue.g;
 a:=pValue.b;
end;
function TVector4.GetRBAR:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetRBAG:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=a;
 result.a:=g;
end;
procedure TVector4.SetRBAG(const pValue:TVector4);
begin
 r:=pValue.r;
 b:=pValue.g;
 a:=pValue.b;
 g:=pValue.a;
end;
function TVector4.GetRBAB:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetRBAA:TVector4;
begin
 result.r:=r;
 result.g:=b;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetRA:TVector2;
begin
 result.r:=r;
 result.g:=a;
end;
procedure TVector4.SetRA(const pValue:TVector2);
begin
 r:=pValue.r;
 a:=pValue.g;
end;
function TVector4.GetRAR:TVector3;
begin
 result.r:=r;
 result.g:=a;
 result.b:=r;
end;
function TVector4.GetRARR:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetRARG:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetRARB:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetRARA:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetRAG:TVector3;
begin
 result.r:=r;
 result.g:=a;
 result.b:=g;
end;
procedure TVector4.SetRAG(const pValue:TVector3);
begin
 r:=pValue.r;
 a:=pValue.g;
 g:=pValue.b;
end;
function TVector4.GetRAGR:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetRAGG:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetRAGB:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=g;
 result.a:=b;
end;
procedure TVector4.SetRAGB(const pValue:TVector4);
begin
 r:=pValue.r;
 a:=pValue.g;
 g:=pValue.b;
 b:=pValue.a;
end;
function TVector4.GetRAGA:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetRAB:TVector3;
begin
 result.r:=r;
 result.g:=a;
 result.b:=b;
end;
procedure TVector4.SetRAB(const pValue:TVector3);
begin
 r:=pValue.r;
 a:=pValue.g;
 b:=pValue.b;
end;
function TVector4.GetRABR:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetRABG:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=b;
 result.a:=g;
end;
procedure TVector4.SetRABG(const pValue:TVector4);
begin
 r:=pValue.r;
 a:=pValue.g;
 b:=pValue.b;
 g:=pValue.a;
end;
function TVector4.GetRABB:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetRABA:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetRAA:TVector3;
begin
 result.r:=r;
 result.g:=a;
 result.b:=a;
end;
function TVector4.GetRAAR:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetRAAG:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetRAAB:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetRAAA:TVector4;
begin
 result.r:=r;
 result.g:=a;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetGR:TVector2;
begin
 result.r:=g;
 result.g:=r;
end;
procedure TVector4.SetGR(const pValue:TVector2);
begin
 g:=pValue.r;
 r:=pValue.g;
end;
function TVector4.GetGRR:TVector3;
begin
 result.r:=g;
 result.g:=r;
 result.b:=r;
end;
function TVector4.GetGRRR:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetGRRG:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetGRRB:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetGRRA:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetGRG:TVector3;
begin
 result.r:=g;
 result.g:=r;
 result.b:=g;
end;
function TVector4.GetGRGR:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetGRGG:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetGRGB:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetGRGA:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetGRB:TVector3;
begin
 result.r:=g;
 result.g:=r;
 result.b:=b;
end;
procedure TVector4.SetGRB(const pValue:TVector3);
begin
 g:=pValue.r;
 r:=pValue.g;
 b:=pValue.b;
end;
function TVector4.GetGRBR:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetGRBG:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetGRBB:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetGRBA:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=b;
 result.a:=a;
end;
procedure TVector4.SetGRBA(const pValue:TVector4);
begin
 g:=pValue.r;
 r:=pValue.g;
 b:=pValue.b;
 a:=pValue.a;
end;
function TVector4.GetGRA:TVector3;
begin
 result.r:=g;
 result.g:=r;
 result.b:=a;
end;
procedure TVector4.SetGRA(const pValue:TVector3);
begin
 g:=pValue.r;
 r:=pValue.g;
 a:=pValue.b;
end;
function TVector4.GetGRAR:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetGRAG:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetGRAB:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=a;
 result.a:=b;
end;
procedure TVector4.SetGRAB(const pValue:TVector4);
begin
 g:=pValue.r;
 r:=pValue.g;
 a:=pValue.b;
 b:=pValue.a;
end;
function TVector4.GetGRAA:TVector4;
begin
 result.r:=g;
 result.g:=r;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetGG:TVector2;
begin
 result.r:=g;
 result.g:=g;
end;
function TVector4.GetGGR:TVector3;
begin
 result.r:=g;
 result.g:=g;
 result.b:=r;
end;
function TVector4.GetGGRR:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetGGRG:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetGGRB:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetGGRA:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetGGG:TVector3;
begin
 result.r:=g;
 result.g:=g;
 result.b:=g;
end;
function TVector4.GetGGGR:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetGGGG:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetGGGB:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetGGGA:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetGGB:TVector3;
begin
 result.r:=g;
 result.g:=g;
 result.b:=b;
end;
function TVector4.GetGGBR:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetGGBG:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetGGBB:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetGGBA:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetGGA:TVector3;
begin
 result.r:=g;
 result.g:=g;
 result.b:=a;
end;
function TVector4.GetGGAR:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetGGAG:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetGGAB:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetGGAA:TVector4;
begin
 result.r:=g;
 result.g:=g;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetGB:TVector2;
begin
 result.r:=g;
 result.g:=b;
end;
procedure TVector4.SetGB(const pValue:TVector2);
begin
 g:=pValue.r;
 b:=pValue.g;
end;
function TVector4.GetGBR:TVector3;
begin
 result.r:=g;
 result.g:=b;
 result.b:=r;
end;
procedure TVector4.SetGBR(const pValue:TVector3);
begin
 g:=pValue.r;
 b:=pValue.g;
 r:=pValue.b;
end;
function TVector4.GetGBRR:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetGBRG:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetGBRB:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetGBRA:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=r;
 result.a:=a;
end;
procedure TVector4.SetGBRA(const pValue:TVector4);
begin
 g:=pValue.r;
 b:=pValue.g;
 r:=pValue.b;
 a:=pValue.a;
end;
function TVector4.GetGBG:TVector3;
begin
 result.r:=g;
 result.g:=b;
 result.b:=g;
end;
function TVector4.GetGBGR:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetGBGG:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetGBGB:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetGBGA:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetGBB:TVector3;
begin
 result.r:=g;
 result.g:=b;
 result.b:=b;
end;
function TVector4.GetGBBR:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetGBBG:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetGBBB:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetGBBA:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetGBA:TVector3;
begin
 result.r:=g;
 result.g:=b;
 result.b:=a;
end;
procedure TVector4.SetGBA(const pValue:TVector3);
begin
 g:=pValue.r;
 b:=pValue.g;
 a:=pValue.b;
end;
function TVector4.GetGBAR:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=a;
 result.a:=r;
end;
procedure TVector4.SetGBAR(const pValue:TVector4);
begin
 g:=pValue.r;
 b:=pValue.g;
 a:=pValue.b;
 r:=pValue.a;
end;
function TVector4.GetGBAG:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetGBAB:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetGBAA:TVector4;
begin
 result.r:=g;
 result.g:=b;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetGA:TVector2;
begin
 result.r:=g;
 result.g:=a;
end;
procedure TVector4.SetGA(const pValue:TVector2);
begin
 g:=pValue.r;
 a:=pValue.g;
end;
function TVector4.GetGAR:TVector3;
begin
 result.r:=g;
 result.g:=a;
 result.b:=r;
end;
procedure TVector4.SetGAR(const pValue:TVector3);
begin
 g:=pValue.r;
 a:=pValue.g;
 r:=pValue.b;
end;
function TVector4.GetGARR:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetGARG:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetGARB:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=r;
 result.a:=b;
end;
procedure TVector4.SetGARB(const pValue:TVector4);
begin
 g:=pValue.r;
 a:=pValue.g;
 r:=pValue.b;
 b:=pValue.a;
end;
function TVector4.GetGARA:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetGAG:TVector3;
begin
 result.r:=g;
 result.g:=a;
 result.b:=g;
end;
function TVector4.GetGAGR:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetGAGG:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetGAGB:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetGAGA:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetGAB:TVector3;
begin
 result.r:=g;
 result.g:=a;
 result.b:=b;
end;
procedure TVector4.SetGAB(const pValue:TVector3);
begin
 g:=pValue.r;
 a:=pValue.g;
 b:=pValue.b;
end;
function TVector4.GetGABR:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=b;
 result.a:=r;
end;
procedure TVector4.SetGABR(const pValue:TVector4);
begin
 g:=pValue.r;
 a:=pValue.g;
 b:=pValue.b;
 r:=pValue.a;
end;
function TVector4.GetGABG:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetGABB:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetGABA:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetGAA:TVector3;
begin
 result.r:=g;
 result.g:=a;
 result.b:=a;
end;
function TVector4.GetGAAR:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetGAAG:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetGAAB:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetGAAA:TVector4;
begin
 result.r:=g;
 result.g:=a;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetBR:TVector2;
begin
 result.r:=b;
 result.g:=r;
end;
procedure TVector4.SetBR(const pValue:TVector2);
begin
 b:=pValue.r;
 r:=pValue.g;
end;
function TVector4.GetBRR:TVector3;
begin
 result.r:=b;
 result.g:=r;
 result.b:=r;
end;
function TVector4.GetBRRR:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetBRRG:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetBRRB:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetBRRA:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetBRG:TVector3;
begin
 result.r:=b;
 result.g:=r;
 result.b:=g;
end;
procedure TVector4.SetBRG(const pValue:TVector3);
begin
 b:=pValue.r;
 r:=pValue.g;
 g:=pValue.b;
end;
function TVector4.GetBRGR:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetBRGG:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetBRGB:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetBRGA:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=g;
 result.a:=a;
end;
procedure TVector4.SetBRGA(const pValue:TVector4);
begin
 b:=pValue.r;
 r:=pValue.g;
 g:=pValue.b;
 a:=pValue.a;
end;
function TVector4.GetBRB:TVector3;
begin
 result.r:=b;
 result.g:=r;
 result.b:=b;
end;
function TVector4.GetBRBR:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetBRBG:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetBRBB:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetBRBA:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetBRA:TVector3;
begin
 result.r:=b;
 result.g:=r;
 result.b:=a;
end;
procedure TVector4.SetBRA(const pValue:TVector3);
begin
 b:=pValue.r;
 r:=pValue.g;
 a:=pValue.b;
end;
function TVector4.GetBRAR:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetBRAG:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=a;
 result.a:=g;
end;
procedure TVector4.SetBRAG(const pValue:TVector4);
begin
 b:=pValue.r;
 r:=pValue.g;
 a:=pValue.b;
 g:=pValue.a;
end;
function TVector4.GetBRAB:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetBRAA:TVector4;
begin
 result.r:=b;
 result.g:=r;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetBG:TVector2;
begin
 result.r:=b;
 result.g:=g;
end;
procedure TVector4.SetBG(const pValue:TVector2);
begin
 b:=pValue.r;
 g:=pValue.g;
end;
function TVector4.GetBGR:TVector3;
begin
 result.r:=b;
 result.g:=g;
 result.b:=r;
end;
procedure TVector4.SetBGR(const pValue:TVector3);
begin
 b:=pValue.r;
 g:=pValue.g;
 r:=pValue.b;
end;
function TVector4.GetBGRR:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetBGRG:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetBGRB:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetBGRA:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=r;
 result.a:=a;
end;
procedure TVector4.SetBGRA(const pValue:TVector4);
begin
 b:=pValue.r;
 g:=pValue.g;
 r:=pValue.b;
 a:=pValue.a;
end;
function TVector4.GetBGG:TVector3;
begin
 result.r:=b;
 result.g:=g;
 result.b:=g;
end;
function TVector4.GetBGGR:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetBGGG:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetBGGB:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetBGGA:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetBGB:TVector3;
begin
 result.r:=b;
 result.g:=g;
 result.b:=b;
end;
function TVector4.GetBGBR:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetBGBG:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetBGBB:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetBGBA:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetBGA:TVector3;
begin
 result.r:=b;
 result.g:=g;
 result.b:=a;
end;
procedure TVector4.SetBGA(const pValue:TVector3);
begin
 b:=pValue.r;
 g:=pValue.g;
 a:=pValue.b;
end;
function TVector4.GetBGAR:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=a;
 result.a:=r;
end;
procedure TVector4.SetBGAR(const pValue:TVector4);
begin
 b:=pValue.r;
 g:=pValue.g;
 a:=pValue.b;
 r:=pValue.a;
end;
function TVector4.GetBGAG:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetBGAB:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetBGAA:TVector4;
begin
 result.r:=b;
 result.g:=g;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetBB:TVector2;
begin
 result.r:=b;
 result.g:=b;
end;
function TVector4.GetBBR:TVector3;
begin
 result.r:=b;
 result.g:=b;
 result.b:=r;
end;
function TVector4.GetBBRR:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetBBRG:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetBBRB:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetBBRA:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetBBG:TVector3;
begin
 result.r:=b;
 result.g:=b;
 result.b:=g;
end;
function TVector4.GetBBGR:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetBBGG:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetBBGB:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetBBGA:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetBBB:TVector3;
begin
 result.r:=b;
 result.g:=b;
 result.b:=b;
end;
function TVector4.GetBBBR:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetBBBG:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetBBBB:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetBBBA:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetBBA:TVector3;
begin
 result.r:=b;
 result.g:=b;
 result.b:=a;
end;
function TVector4.GetBBAR:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetBBAG:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetBBAB:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetBBAA:TVector4;
begin
 result.r:=b;
 result.g:=b;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetBA:TVector2;
begin
 result.r:=b;
 result.g:=a;
end;
procedure TVector4.SetBA(const pValue:TVector2);
begin
 b:=pValue.r;
 a:=pValue.g;
end;
function TVector4.GetBAR:TVector3;
begin
 result.r:=b;
 result.g:=a;
 result.b:=r;
end;
procedure TVector4.SetBAR(const pValue:TVector3);
begin
 b:=pValue.r;
 a:=pValue.g;
 r:=pValue.b;
end;
function TVector4.GetBARR:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetBARG:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=r;
 result.a:=g;
end;
procedure TVector4.SetBARG(const pValue:TVector4);
begin
 b:=pValue.r;
 a:=pValue.g;
 r:=pValue.b;
 g:=pValue.a;
end;
function TVector4.GetBARB:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetBARA:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetBAG:TVector3;
begin
 result.r:=b;
 result.g:=a;
 result.b:=g;
end;
procedure TVector4.SetBAG(const pValue:TVector3);
begin
 b:=pValue.r;
 a:=pValue.g;
 g:=pValue.b;
end;
function TVector4.GetBAGR:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=g;
 result.a:=r;
end;
procedure TVector4.SetBAGR(const pValue:TVector4);
begin
 b:=pValue.r;
 a:=pValue.g;
 g:=pValue.b;
 r:=pValue.a;
end;
function TVector4.GetBAGG:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetBAGB:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetBAGA:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetBAB:TVector3;
begin
 result.r:=b;
 result.g:=a;
 result.b:=b;
end;
function TVector4.GetBABR:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetBABG:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetBABB:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetBABA:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetBAA:TVector3;
begin
 result.r:=b;
 result.g:=a;
 result.b:=a;
end;
function TVector4.GetBAAR:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetBAAG:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetBAAB:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetBAAA:TVector4;
begin
 result.r:=b;
 result.g:=a;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetAR:TVector2;
begin
 result.r:=a;
 result.g:=r;
end;
procedure TVector4.SetAR(const pValue:TVector2);
begin
 a:=pValue.r;
 r:=pValue.g;
end;
function TVector4.GetARR:TVector3;
begin
 result.r:=a;
 result.g:=r;
 result.b:=r;
end;
function TVector4.GetARRR:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetARRG:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetARRB:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetARRA:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetARG:TVector3;
begin
 result.r:=a;
 result.g:=r;
 result.b:=g;
end;
procedure TVector4.SetARG(const pValue:TVector3);
begin
 a:=pValue.r;
 r:=pValue.g;
 g:=pValue.b;
end;
function TVector4.GetARGR:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetARGG:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetARGB:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=g;
 result.a:=b;
end;
procedure TVector4.SetARGB(const pValue:TVector4);
begin
 a:=pValue.r;
 r:=pValue.g;
 g:=pValue.b;
 b:=pValue.a;
end;
function TVector4.GetARGA:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetARB:TVector3;
begin
 result.r:=a;
 result.g:=r;
 result.b:=b;
end;
procedure TVector4.SetARB(const pValue:TVector3);
begin
 a:=pValue.r;
 r:=pValue.g;
 b:=pValue.b;
end;
function TVector4.GetARBR:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetARBG:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=b;
 result.a:=g;
end;
procedure TVector4.SetARBG(const pValue:TVector4);
begin
 a:=pValue.r;
 r:=pValue.g;
 b:=pValue.b;
 g:=pValue.a;
end;
function TVector4.GetARBB:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetARBA:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetARA:TVector3;
begin
 result.r:=a;
 result.g:=r;
 result.b:=a;
end;
function TVector4.GetARAR:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetARAG:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetARAB:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetARAA:TVector4;
begin
 result.r:=a;
 result.g:=r;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetAG:TVector2;
begin
 result.r:=a;
 result.g:=g;
end;
procedure TVector4.SetAG(const pValue:TVector2);
begin
 a:=pValue.r;
 g:=pValue.g;
end;
function TVector4.GetAGR:TVector3;
begin
 result.r:=a;
 result.g:=g;
 result.b:=r;
end;
procedure TVector4.SetAGR(const pValue:TVector3);
begin
 a:=pValue.r;
 g:=pValue.g;
 r:=pValue.b;
end;
function TVector4.GetAGRR:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetAGRG:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetAGRB:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=r;
 result.a:=b;
end;
procedure TVector4.SetAGRB(const pValue:TVector4);
begin
 a:=pValue.r;
 g:=pValue.g;
 r:=pValue.b;
 b:=pValue.a;
end;
function TVector4.GetAGRA:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetAGG:TVector3;
begin
 result.r:=a;
 result.g:=g;
 result.b:=g;
end;
function TVector4.GetAGGR:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetAGGG:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetAGGB:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetAGGA:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetAGB:TVector3;
begin
 result.r:=a;
 result.g:=g;
 result.b:=b;
end;
procedure TVector4.SetAGB(const pValue:TVector3);
begin
 a:=pValue.r;
 g:=pValue.g;
 b:=pValue.b;
end;
function TVector4.GetAGBR:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=b;
 result.a:=r;
end;
procedure TVector4.SetAGBR(const pValue:TVector4);
begin
 a:=pValue.r;
 g:=pValue.g;
 b:=pValue.b;
 r:=pValue.a;
end;
function TVector4.GetAGBG:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetAGBB:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetAGBA:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetAGA:TVector3;
begin
 result.r:=a;
 result.g:=g;
 result.b:=a;
end;
function TVector4.GetAGAR:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetAGAG:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetAGAB:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetAGAA:TVector4;
begin
 result.r:=a;
 result.g:=g;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetAB:TVector2;
begin
 result.r:=a;
 result.g:=b;
end;
procedure TVector4.SetAB(const pValue:TVector2);
begin
 a:=pValue.r;
 b:=pValue.g;
end;
function TVector4.GetABR:TVector3;
begin
 result.r:=a;
 result.g:=b;
 result.b:=r;
end;
procedure TVector4.SetABR(const pValue:TVector3);
begin
 a:=pValue.r;
 b:=pValue.g;
 r:=pValue.b;
end;
function TVector4.GetABRR:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetABRG:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=r;
 result.a:=g;
end;
procedure TVector4.SetABRG(const pValue:TVector4);
begin
 a:=pValue.r;
 b:=pValue.g;
 r:=pValue.b;
 g:=pValue.a;
end;
function TVector4.GetABRB:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetABRA:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetABG:TVector3;
begin
 result.r:=a;
 result.g:=b;
 result.b:=g;
end;
procedure TVector4.SetABG(const pValue:TVector3);
begin
 a:=pValue.r;
 b:=pValue.g;
 g:=pValue.b;
end;
function TVector4.GetABGR:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=g;
 result.a:=r;
end;
procedure TVector4.SetABGR(const pValue:TVector4);
begin
 a:=pValue.r;
 b:=pValue.g;
 g:=pValue.b;
 r:=pValue.a;
end;
function TVector4.GetABGG:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetABGB:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetABGA:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetABB:TVector3;
begin
 result.r:=a;
 result.g:=b;
 result.b:=b;
end;
function TVector4.GetABBR:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetABBG:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetABBB:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetABBA:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetABA:TVector3;
begin
 result.r:=a;
 result.g:=b;
 result.b:=a;
end;
function TVector4.GetABAR:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetABAG:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetABAB:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetABAA:TVector4;
begin
 result.r:=a;
 result.g:=b;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetAA:TVector2;
begin
 result.r:=a;
 result.g:=a;
end;
function TVector4.GetAAR:TVector3;
begin
 result.r:=a;
 result.g:=a;
 result.b:=r;
end;
function TVector4.GetAARR:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=r;
 result.a:=r;
end;
function TVector4.GetAARG:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=r;
 result.a:=g;
end;
function TVector4.GetAARB:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=r;
 result.a:=b;
end;
function TVector4.GetAARA:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=r;
 result.a:=a;
end;
function TVector4.GetAAG:TVector3;
begin
 result.r:=a;
 result.g:=a;
 result.b:=g;
end;
function TVector4.GetAAGR:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=g;
 result.a:=r;
end;
function TVector4.GetAAGG:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=g;
 result.a:=g;
end;
function TVector4.GetAAGB:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=g;
 result.a:=b;
end;
function TVector4.GetAAGA:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=g;
 result.a:=a;
end;
function TVector4.GetAAB:TVector3;
begin
 result.r:=a;
 result.g:=a;
 result.b:=b;
end;
function TVector4.GetAABR:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=b;
 result.a:=r;
end;
function TVector4.GetAABG:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=b;
 result.a:=g;
end;
function TVector4.GetAABB:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=b;
 result.a:=b;
end;
function TVector4.GetAABA:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=b;
 result.a:=a;
end;
function TVector4.GetAAA:TVector3;
begin
 result.r:=a;
 result.g:=a;
 result.b:=a;
end;
function TVector4.GetAAAR:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=a;
 result.a:=r;
end;
function TVector4.GetAAAG:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=a;
 result.a:=g;
end;
function TVector4.GetAAAB:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=a;
 result.a:=b;
end;
function TVector4.GetAAAA:TVector4;
begin
 result.r:=a;
 result.g:=a;
 result.b:=a;
 result.a:=a;
end;
function TVector4.GetSS:TVector2;
begin
 result.s:=s;
 result.t:=s;
end;
function TVector4.GetSSS:TVector3;
begin
 result.s:=s;
 result.t:=s;
 result.p:=s;
end;
function TVector4.GetSSSS:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetSSST:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetSSSP:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetSSSQ:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetSST:TVector3;
begin
 result.s:=s;
 result.t:=s;
 result.p:=t;
end;
function TVector4.GetSSTS:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetSSTT:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetSSTP:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetSSTQ:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetSSP:TVector3;
begin
 result.s:=s;
 result.t:=s;
 result.p:=p;
end;
function TVector4.GetSSPS:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetSSPT:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetSSPP:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetSSPQ:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetSSQ:TVector3;
begin
 result.s:=s;
 result.t:=s;
 result.p:=q;
end;
function TVector4.GetSSQS:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetSSQT:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetSSQP:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetSSQQ:TVector4;
begin
 result.s:=s;
 result.t:=s;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetST:TVector2;
begin
 result.s:=s;
 result.t:=t;
end;
procedure TVector4.SetST(const pValue:TVector2);
begin
 s:=pValue.s;
 t:=pValue.t;
end;
function TVector4.GetSTS:TVector3;
begin
 result.s:=s;
 result.t:=t;
 result.p:=s;
end;
function TVector4.GetSTSS:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetSTST:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetSTSP:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetSTSQ:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetSTT:TVector3;
begin
 result.s:=s;
 result.t:=t;
 result.p:=t;
end;
function TVector4.GetSTTS:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetSTTT:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetSTTP:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetSTTQ:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetSTP:TVector3;
begin
 result.s:=s;
 result.t:=t;
 result.p:=p;
end;
procedure TVector4.SetSTP(const pValue:TVector3);
begin
 s:=pValue.s;
 t:=pValue.t;
 p:=pValue.p;
end;
function TVector4.GetSTPS:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetSTPT:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetSTPP:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetSTPQ:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=p;
 result.q:=q;
end;
procedure TVector4.SetSTPQ(const pValue:TVector4);
begin
 s:=pValue.s;
 t:=pValue.t;
 p:=pValue.p;
 q:=pValue.q;
end;
function TVector4.GetSTQ:TVector3;
begin
 result.s:=s;
 result.t:=t;
 result.p:=q;
end;
procedure TVector4.SetSTQ(const pValue:TVector3);
begin
 s:=pValue.s;
 t:=pValue.t;
 q:=pValue.p;
end;
function TVector4.GetSTQS:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetSTQT:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetSTQP:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=q;
 result.q:=p;
end;
procedure TVector4.SetSTQP(const pValue:TVector4);
begin
 s:=pValue.s;
 t:=pValue.t;
 q:=pValue.p;
 p:=pValue.q;
end;
function TVector4.GetSTQQ:TVector4;
begin
 result.s:=s;
 result.t:=t;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetSP:TVector2;
begin
 result.s:=s;
 result.t:=p;
end;
procedure TVector4.SetSP(const pValue:TVector2);
begin
 s:=pValue.s;
 p:=pValue.t;
end;
function TVector4.GetSPS:TVector3;
begin
 result.s:=s;
 result.t:=p;
 result.p:=s;
end;
function TVector4.GetSPSS:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetSPST:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetSPSP:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetSPSQ:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetSPT:TVector3;
begin
 result.s:=s;
 result.t:=p;
 result.p:=t;
end;
procedure TVector4.SetSPT(const pValue:TVector3);
begin
 s:=pValue.s;
 p:=pValue.t;
 t:=pValue.p;
end;
function TVector4.GetSPTS:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetSPTT:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetSPTP:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetSPTQ:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=t;
 result.q:=q;
end;
procedure TVector4.SetSPTQ(const pValue:TVector4);
begin
 s:=pValue.s;
 p:=pValue.t;
 t:=pValue.p;
 q:=pValue.q;
end;
function TVector4.GetSPP:TVector3;
begin
 result.s:=s;
 result.t:=p;
 result.p:=p;
end;
function TVector4.GetSPPS:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetSPPT:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetSPPP:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetSPPQ:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetSPQ:TVector3;
begin
 result.s:=s;
 result.t:=p;
 result.p:=q;
end;
procedure TVector4.SetSPQ(const pValue:TVector3);
begin
 s:=pValue.s;
 p:=pValue.t;
 q:=pValue.p;
end;
function TVector4.GetSPQS:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetSPQT:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=q;
 result.q:=t;
end;
procedure TVector4.SetSPQT(const pValue:TVector4);
begin
 s:=pValue.s;
 p:=pValue.t;
 q:=pValue.p;
 t:=pValue.q;
end;
function TVector4.GetSPQP:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetSPQQ:TVector4;
begin
 result.s:=s;
 result.t:=p;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetSQ:TVector2;
begin
 result.s:=s;
 result.t:=q;
end;
procedure TVector4.SetSQ(const pValue:TVector2);
begin
 s:=pValue.s;
 q:=pValue.t;
end;
function TVector4.GetSQS:TVector3;
begin
 result.s:=s;
 result.t:=q;
 result.p:=s;
end;
function TVector4.GetSQSS:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetSQST:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetSQSP:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetSQSQ:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetSQT:TVector3;
begin
 result.s:=s;
 result.t:=q;
 result.p:=t;
end;
procedure TVector4.SetSQT(const pValue:TVector3);
begin
 s:=pValue.s;
 q:=pValue.t;
 t:=pValue.p;
end;
function TVector4.GetSQTS:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetSQTT:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetSQTP:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=t;
 result.q:=p;
end;
procedure TVector4.SetSQTP(const pValue:TVector4);
begin
 s:=pValue.s;
 q:=pValue.t;
 t:=pValue.p;
 p:=pValue.q;
end;
function TVector4.GetSQTQ:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetSQP:TVector3;
begin
 result.s:=s;
 result.t:=q;
 result.p:=p;
end;
procedure TVector4.SetSQP(const pValue:TVector3);
begin
 s:=pValue.s;
 q:=pValue.t;
 p:=pValue.p;
end;
function TVector4.GetSQPS:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetSQPT:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=p;
 result.q:=t;
end;
procedure TVector4.SetSQPT(const pValue:TVector4);
begin
 s:=pValue.s;
 q:=pValue.t;
 p:=pValue.p;
 t:=pValue.q;
end;
function TVector4.GetSQPP:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetSQPQ:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetSQQ:TVector3;
begin
 result.s:=s;
 result.t:=q;
 result.p:=q;
end;
function TVector4.GetSQQS:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetSQQT:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetSQQP:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetSQQQ:TVector4;
begin
 result.s:=s;
 result.t:=q;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetTS:TVector2;
begin
 result.s:=t;
 result.t:=s;
end;
procedure TVector4.SetTS(const pValue:TVector2);
begin
 t:=pValue.s;
 s:=pValue.t;
end;
function TVector4.GetTSS:TVector3;
begin
 result.s:=t;
 result.t:=s;
 result.p:=s;
end;
function TVector4.GetTSSS:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetTSST:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetTSSP:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetTSSQ:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetTST:TVector3;
begin
 result.s:=t;
 result.t:=s;
 result.p:=t;
end;
function TVector4.GetTSTS:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetTSTT:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetTSTP:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetTSTQ:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetTSP:TVector3;
begin
 result.s:=t;
 result.t:=s;
 result.p:=p;
end;
procedure TVector4.SetTSP(const pValue:TVector3);
begin
 t:=pValue.s;
 s:=pValue.t;
 p:=pValue.p;
end;
function TVector4.GetTSPS:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetTSPT:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetTSPP:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetTSPQ:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=p;
 result.q:=q;
end;
procedure TVector4.SetTSPQ(const pValue:TVector4);
begin
 t:=pValue.s;
 s:=pValue.t;
 p:=pValue.p;
 q:=pValue.q;
end;
function TVector4.GetTSQ:TVector3;
begin
 result.s:=t;
 result.t:=s;
 result.p:=q;
end;
procedure TVector4.SetTSQ(const pValue:TVector3);
begin
 t:=pValue.s;
 s:=pValue.t;
 q:=pValue.p;
end;
function TVector4.GetTSQS:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetTSQT:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetTSQP:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=q;
 result.q:=p;
end;
procedure TVector4.SetTSQP(const pValue:TVector4);
begin
 t:=pValue.s;
 s:=pValue.t;
 q:=pValue.p;
 p:=pValue.q;
end;
function TVector4.GetTSQQ:TVector4;
begin
 result.s:=t;
 result.t:=s;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetTT:TVector2;
begin
 result.s:=t;
 result.t:=t;
end;
function TVector4.GetTTS:TVector3;
begin
 result.s:=t;
 result.t:=t;
 result.p:=s;
end;
function TVector4.GetTTSS:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetTTST:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetTTSP:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetTTSQ:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetTTT:TVector3;
begin
 result.s:=t;
 result.t:=t;
 result.p:=t;
end;
function TVector4.GetTTTS:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetTTTT:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetTTTP:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetTTTQ:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetTTP:TVector3;
begin
 result.s:=t;
 result.t:=t;
 result.p:=p;
end;
function TVector4.GetTTPS:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetTTPT:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetTTPP:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetTTPQ:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetTTQ:TVector3;
begin
 result.s:=t;
 result.t:=t;
 result.p:=q;
end;
function TVector4.GetTTQS:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetTTQT:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetTTQP:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetTTQQ:TVector4;
begin
 result.s:=t;
 result.t:=t;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetTP:TVector2;
begin
 result.s:=t;
 result.t:=p;
end;
procedure TVector4.SetTP(const pValue:TVector2);
begin
 t:=pValue.s;
 p:=pValue.t;
end;
function TVector4.GetTPS:TVector3;
begin
 result.s:=t;
 result.t:=p;
 result.p:=s;
end;
procedure TVector4.SetTPS(const pValue:TVector3);
begin
 t:=pValue.s;
 p:=pValue.t;
 s:=pValue.p;
end;
function TVector4.GetTPSS:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetTPST:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetTPSP:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetTPSQ:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=s;
 result.q:=q;
end;
procedure TVector4.SetTPSQ(const pValue:TVector4);
begin
 t:=pValue.s;
 p:=pValue.t;
 s:=pValue.p;
 q:=pValue.q;
end;
function TVector4.GetTPT:TVector3;
begin
 result.s:=t;
 result.t:=p;
 result.p:=t;
end;
function TVector4.GetTPTS:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetTPTT:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetTPTP:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetTPTQ:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetTPP:TVector3;
begin
 result.s:=t;
 result.t:=p;
 result.p:=p;
end;
function TVector4.GetTPPS:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetTPPT:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetTPPP:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetTPPQ:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetTPQ:TVector3;
begin
 result.s:=t;
 result.t:=p;
 result.p:=q;
end;
procedure TVector4.SetTPQ(const pValue:TVector3);
begin
 t:=pValue.s;
 p:=pValue.t;
 q:=pValue.p;
end;
function TVector4.GetTPQS:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=q;
 result.q:=s;
end;
procedure TVector4.SetTPQS(const pValue:TVector4);
begin
 t:=pValue.s;
 p:=pValue.t;
 q:=pValue.p;
 s:=pValue.q;
end;
function TVector4.GetTPQT:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetTPQP:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetTPQQ:TVector4;
begin
 result.s:=t;
 result.t:=p;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetTQ:TVector2;
begin
 result.s:=t;
 result.t:=q;
end;
procedure TVector4.SetTQ(const pValue:TVector2);
begin
 t:=pValue.s;
 q:=pValue.t;
end;
function TVector4.GetTQS:TVector3;
begin
 result.s:=t;
 result.t:=q;
 result.p:=s;
end;
procedure TVector4.SetTQS(const pValue:TVector3);
begin
 t:=pValue.s;
 q:=pValue.t;
 s:=pValue.p;
end;
function TVector4.GetTQSS:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetTQST:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetTQSP:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=s;
 result.q:=p;
end;
procedure TVector4.SetTQSP(const pValue:TVector4);
begin
 t:=pValue.s;
 q:=pValue.t;
 s:=pValue.p;
 p:=pValue.q;
end;
function TVector4.GetTQSQ:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetTQT:TVector3;
begin
 result.s:=t;
 result.t:=q;
 result.p:=t;
end;
function TVector4.GetTQTS:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetTQTT:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetTQTP:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetTQTQ:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetTQP:TVector3;
begin
 result.s:=t;
 result.t:=q;
 result.p:=p;
end;
procedure TVector4.SetTQP(const pValue:TVector3);
begin
 t:=pValue.s;
 q:=pValue.t;
 p:=pValue.p;
end;
function TVector4.GetTQPS:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=p;
 result.q:=s;
end;
procedure TVector4.SetTQPS(const pValue:TVector4);
begin
 t:=pValue.s;
 q:=pValue.t;
 p:=pValue.p;
 s:=pValue.q;
end;
function TVector4.GetTQPT:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetTQPP:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetTQPQ:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetTQQ:TVector3;
begin
 result.s:=t;
 result.t:=q;
 result.p:=q;
end;
function TVector4.GetTQQS:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetTQQT:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetTQQP:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetTQQQ:TVector4;
begin
 result.s:=t;
 result.t:=q;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetPS:TVector2;
begin
 result.s:=p;
 result.t:=s;
end;
procedure TVector4.SetPS(const pValue:TVector2);
begin
 p:=pValue.s;
 s:=pValue.t;
end;
function TVector4.GetPSS:TVector3;
begin
 result.s:=p;
 result.t:=s;
 result.p:=s;
end;
function TVector4.GetPSSS:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetPSST:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetPSSP:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetPSSQ:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetPST:TVector3;
begin
 result.s:=p;
 result.t:=s;
 result.p:=t;
end;
procedure TVector4.SetPST(const pValue:TVector3);
begin
 p:=pValue.s;
 s:=pValue.t;
 t:=pValue.p;
end;
function TVector4.GetPSTS:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetPSTT:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetPSTP:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetPSTQ:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=t;
 result.q:=q;
end;
procedure TVector4.SetPSTQ(const pValue:TVector4);
begin
 p:=pValue.s;
 s:=pValue.t;
 t:=pValue.p;
 q:=pValue.q;
end;
function TVector4.GetPSP:TVector3;
begin
 result.s:=p;
 result.t:=s;
 result.p:=p;
end;
function TVector4.GetPSPS:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetPSPT:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetPSPP:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetPSPQ:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetPSQ:TVector3;
begin
 result.s:=p;
 result.t:=s;
 result.p:=q;
end;
procedure TVector4.SetPSQ(const pValue:TVector3);
begin
 p:=pValue.s;
 s:=pValue.t;
 q:=pValue.p;
end;
function TVector4.GetPSQS:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetPSQT:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=q;
 result.q:=t;
end;
procedure TVector4.SetPSQT(const pValue:TVector4);
begin
 p:=pValue.s;
 s:=pValue.t;
 q:=pValue.p;
 t:=pValue.q;
end;
function TVector4.GetPSQP:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetPSQQ:TVector4;
begin
 result.s:=p;
 result.t:=s;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetPT:TVector2;
begin
 result.s:=p;
 result.t:=t;
end;
procedure TVector4.SetPT(const pValue:TVector2);
begin
 p:=pValue.s;
 t:=pValue.t;
end;
function TVector4.GetPTS:TVector3;
begin
 result.s:=p;
 result.t:=t;
 result.p:=s;
end;
procedure TVector4.SetPTS(const pValue:TVector3);
begin
 p:=pValue.s;
 t:=pValue.t;
 s:=pValue.p;
end;
function TVector4.GetPTSS:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetPTST:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetPTSP:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetPTSQ:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=s;
 result.q:=q;
end;
procedure TVector4.SetPTSQ(const pValue:TVector4);
begin
 p:=pValue.s;
 t:=pValue.t;
 s:=pValue.p;
 q:=pValue.q;
end;
function TVector4.GetPTT:TVector3;
begin
 result.s:=p;
 result.t:=t;
 result.p:=t;
end;
function TVector4.GetPTTS:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetPTTT:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetPTTP:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetPTTQ:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetPTP:TVector3;
begin
 result.s:=p;
 result.t:=t;
 result.p:=p;
end;
function TVector4.GetPTPS:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetPTPT:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetPTPP:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetPTPQ:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetPTQ:TVector3;
begin
 result.s:=p;
 result.t:=t;
 result.p:=q;
end;
procedure TVector4.SetPTQ(const pValue:TVector3);
begin
 p:=pValue.s;
 t:=pValue.t;
 q:=pValue.p;
end;
function TVector4.GetPTQS:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=q;
 result.q:=s;
end;
procedure TVector4.SetPTQS(const pValue:TVector4);
begin
 p:=pValue.s;
 t:=pValue.t;
 q:=pValue.p;
 s:=pValue.q;
end;
function TVector4.GetPTQT:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetPTQP:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetPTQQ:TVector4;
begin
 result.s:=p;
 result.t:=t;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetPP:TVector2;
begin
 result.s:=p;
 result.t:=p;
end;
function TVector4.GetPPS:TVector3;
begin
 result.s:=p;
 result.t:=p;
 result.p:=s;
end;
function TVector4.GetPPSS:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetPPST:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetPPSP:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetPPSQ:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetPPT:TVector3;
begin
 result.s:=p;
 result.t:=p;
 result.p:=t;
end;
function TVector4.GetPPTS:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetPPTT:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetPPTP:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetPPTQ:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetPPP:TVector3;
begin
 result.s:=p;
 result.t:=p;
 result.p:=p;
end;
function TVector4.GetPPPS:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetPPPT:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetPPPP:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetPPPQ:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetPPQ:TVector3;
begin
 result.s:=p;
 result.t:=p;
 result.p:=q;
end;
function TVector4.GetPPQS:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetPPQT:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetPPQP:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetPPQQ:TVector4;
begin
 result.s:=p;
 result.t:=p;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetPQ:TVector2;
begin
 result.s:=p;
 result.t:=q;
end;
procedure TVector4.SetPQ(const pValue:TVector2);
begin
 p:=pValue.s;
 q:=pValue.t;
end;
function TVector4.GetPQS:TVector3;
begin
 result.s:=p;
 result.t:=q;
 result.p:=s;
end;
procedure TVector4.SetPQS(const pValue:TVector3);
begin
 p:=pValue.s;
 q:=pValue.t;
 s:=pValue.p;
end;
function TVector4.GetPQSS:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetPQST:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=s;
 result.q:=t;
end;
procedure TVector4.SetPQST(const pValue:TVector4);
begin
 p:=pValue.s;
 q:=pValue.t;
 s:=pValue.p;
 t:=pValue.q;
end;
function TVector4.GetPQSP:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetPQSQ:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetPQT:TVector3;
begin
 result.s:=p;
 result.t:=q;
 result.p:=t;
end;
procedure TVector4.SetPQT(const pValue:TVector3);
begin
 p:=pValue.s;
 q:=pValue.t;
 t:=pValue.p;
end;
function TVector4.GetPQTS:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=t;
 result.q:=s;
end;
procedure TVector4.SetPQTS(const pValue:TVector4);
begin
 p:=pValue.s;
 q:=pValue.t;
 t:=pValue.p;
 s:=pValue.q;
end;
function TVector4.GetPQTT:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetPQTP:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetPQTQ:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetPQP:TVector3;
begin
 result.s:=p;
 result.t:=q;
 result.p:=p;
end;
function TVector4.GetPQPS:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetPQPT:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetPQPP:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetPQPQ:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetPQQ:TVector3;
begin
 result.s:=p;
 result.t:=q;
 result.p:=q;
end;
function TVector4.GetPQQS:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetPQQT:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetPQQP:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetPQQQ:TVector4;
begin
 result.s:=p;
 result.t:=q;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetQS:TVector2;
begin
 result.s:=q;
 result.t:=s;
end;
procedure TVector4.SetQS(const pValue:TVector2);
begin
 q:=pValue.s;
 s:=pValue.t;
end;
function TVector4.GetQSS:TVector3;
begin
 result.s:=q;
 result.t:=s;
 result.p:=s;
end;
function TVector4.GetQSSS:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetQSST:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetQSSP:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetQSSQ:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetQST:TVector3;
begin
 result.s:=q;
 result.t:=s;
 result.p:=t;
end;
procedure TVector4.SetQST(const pValue:TVector3);
begin
 q:=pValue.s;
 s:=pValue.t;
 t:=pValue.p;
end;
function TVector4.GetQSTS:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetQSTT:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetQSTP:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=t;
 result.q:=p;
end;
procedure TVector4.SetQSTP(const pValue:TVector4);
begin
 q:=pValue.s;
 s:=pValue.t;
 t:=pValue.p;
 p:=pValue.q;
end;
function TVector4.GetQSTQ:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetQSP:TVector3;
begin
 result.s:=q;
 result.t:=s;
 result.p:=p;
end;
procedure TVector4.SetQSP(const pValue:TVector3);
begin
 q:=pValue.s;
 s:=pValue.t;
 p:=pValue.p;
end;
function TVector4.GetQSPS:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetQSPT:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=p;
 result.q:=t;
end;
procedure TVector4.SetQSPT(const pValue:TVector4);
begin
 q:=pValue.s;
 s:=pValue.t;
 p:=pValue.p;
 t:=pValue.q;
end;
function TVector4.GetQSPP:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetQSPQ:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetQSQ:TVector3;
begin
 result.s:=q;
 result.t:=s;
 result.p:=q;
end;
function TVector4.GetQSQS:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetQSQT:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetQSQP:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetQSQQ:TVector4;
begin
 result.s:=q;
 result.t:=s;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetQT:TVector2;
begin
 result.s:=q;
 result.t:=t;
end;
procedure TVector4.SetQT(const pValue:TVector2);
begin
 q:=pValue.s;
 t:=pValue.t;
end;
function TVector4.GetQTS:TVector3;
begin
 result.s:=q;
 result.t:=t;
 result.p:=s;
end;
procedure TVector4.SetQTS(const pValue:TVector3);
begin
 q:=pValue.s;
 t:=pValue.t;
 s:=pValue.p;
end;
function TVector4.GetQTSS:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetQTST:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetQTSP:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=s;
 result.q:=p;
end;
procedure TVector4.SetQTSP(const pValue:TVector4);
begin
 q:=pValue.s;
 t:=pValue.t;
 s:=pValue.p;
 p:=pValue.q;
end;
function TVector4.GetQTSQ:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetQTT:TVector3;
begin
 result.s:=q;
 result.t:=t;
 result.p:=t;
end;
function TVector4.GetQTTS:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetQTTT:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetQTTP:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetQTTQ:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetQTP:TVector3;
begin
 result.s:=q;
 result.t:=t;
 result.p:=p;
end;
procedure TVector4.SetQTP(const pValue:TVector3);
begin
 q:=pValue.s;
 t:=pValue.t;
 p:=pValue.p;
end;
function TVector4.GetQTPS:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=p;
 result.q:=s;
end;
procedure TVector4.SetQTPS(const pValue:TVector4);
begin
 q:=pValue.s;
 t:=pValue.t;
 p:=pValue.p;
 s:=pValue.q;
end;
function TVector4.GetQTPT:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetQTPP:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetQTPQ:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetQTQ:TVector3;
begin
 result.s:=q;
 result.t:=t;
 result.p:=q;
end;
function TVector4.GetQTQS:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetQTQT:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetQTQP:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetQTQQ:TVector4;
begin
 result.s:=q;
 result.t:=t;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetQP:TVector2;
begin
 result.s:=q;
 result.t:=p;
end;
procedure TVector4.SetQP(const pValue:TVector2);
begin
 q:=pValue.s;
 p:=pValue.t;
end;
function TVector4.GetQPS:TVector3;
begin
 result.s:=q;
 result.t:=p;
 result.p:=s;
end;
procedure TVector4.SetQPS(const pValue:TVector3);
begin
 q:=pValue.s;
 p:=pValue.t;
 s:=pValue.p;
end;
function TVector4.GetQPSS:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetQPST:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=s;
 result.q:=t;
end;
procedure TVector4.SetQPST(const pValue:TVector4);
begin
 q:=pValue.s;
 p:=pValue.t;
 s:=pValue.p;
 t:=pValue.q;
end;
function TVector4.GetQPSP:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetQPSQ:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetQPT:TVector3;
begin
 result.s:=q;
 result.t:=p;
 result.p:=t;
end;
procedure TVector4.SetQPT(const pValue:TVector3);
begin
 q:=pValue.s;
 p:=pValue.t;
 t:=pValue.p;
end;
function TVector4.GetQPTS:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=t;
 result.q:=s;
end;
procedure TVector4.SetQPTS(const pValue:TVector4);
begin
 q:=pValue.s;
 p:=pValue.t;
 t:=pValue.p;
 s:=pValue.q;
end;
function TVector4.GetQPTT:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetQPTP:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetQPTQ:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetQPP:TVector3;
begin
 result.s:=q;
 result.t:=p;
 result.p:=p;
end;
function TVector4.GetQPPS:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetQPPT:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetQPPP:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetQPPQ:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetQPQ:TVector3;
begin
 result.s:=q;
 result.t:=p;
 result.p:=q;
end;
function TVector4.GetQPQS:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetQPQT:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetQPQP:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetQPQQ:TVector4;
begin
 result.s:=q;
 result.t:=p;
 result.p:=q;
 result.q:=q;
end;
function TVector4.GetQQ:TVector2;
begin
 result.s:=q;
 result.t:=q;
end;
function TVector4.GetQQS:TVector3;
begin
 result.s:=q;
 result.t:=q;
 result.p:=s;
end;
function TVector4.GetQQSS:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=s;
 result.q:=s;
end;
function TVector4.GetQQST:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=s;
 result.q:=t;
end;
function TVector4.GetQQSP:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=s;
 result.q:=p;
end;
function TVector4.GetQQSQ:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=s;
 result.q:=q;
end;
function TVector4.GetQQT:TVector3;
begin
 result.s:=q;
 result.t:=q;
 result.p:=t;
end;
function TVector4.GetQQTS:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=t;
 result.q:=s;
end;
function TVector4.GetQQTT:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=t;
 result.q:=t;
end;
function TVector4.GetQQTP:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=t;
 result.q:=p;
end;
function TVector4.GetQQTQ:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=t;
 result.q:=q;
end;
function TVector4.GetQQP:TVector3;
begin
 result.s:=q;
 result.t:=q;
 result.p:=p;
end;
function TVector4.GetQQPS:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=p;
 result.q:=s;
end;
function TVector4.GetQQPT:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=p;
 result.q:=t;
end;
function TVector4.GetQQPP:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=p;
 result.q:=p;
end;
function TVector4.GetQQPQ:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=p;
 result.q:=q;
end;
function TVector4.GetQQQ:TVector3;
begin
 result.s:=q;
 result.t:=q;
 result.p:=q;
end;
function TVector4.GetQQQS:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=q;
 result.q:=s;
end;
function TVector4.GetQQQT:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=q;
 result.q:=t;
end;
function TVector4.GetQQQP:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=q;
 result.q:=p;
end;
function TVector4.GetQQQQ:TVector4;
begin
 result.s:=q;
 result.t:=q;
 result.p:=q;
 result.q:=q;
end;
