private
function GetAA:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAABA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAABB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAABG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAABR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAAR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAARA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAARB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAARG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAARR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAB:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetABA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetABAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetABBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetABGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetABRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetABRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAG:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAGRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetAR:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetARA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetARAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetARBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetARGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetARRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetARRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBA:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBABA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBABB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBABG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBABR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBAR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBARA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBARB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBARG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBARR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBB:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBBRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBG:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBGRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBR:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetBRRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGA:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGABA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGABB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGABG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGABR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGAR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGARA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGARB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGARG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGARR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGB:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGBRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGG:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGGRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGR:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetGRRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPP:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPPTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQ:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPQTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPS:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPST:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPSTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPT:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetPTTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQP:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQPTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQ:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQQTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQS:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQST:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQSTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQT:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetQTTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRA:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRABA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRABB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRABG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRABR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRAR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRARA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRARB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRARG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRARR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRB:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRBRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRG:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRGRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRR:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRA:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRAA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRAB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRAG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRAR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRB:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRBA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRBB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRBG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRBR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRG:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRGA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRGB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRGG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRGR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRR:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRRA:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRRB:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRRG:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetRRRR:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSP:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSPTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQ:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSQTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSS:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSST:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSSTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetST:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetSTTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTP:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTPTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQ:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTQTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTS:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTST:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTSTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTT:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTP:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTPP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTPQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTPS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTPT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTQ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTQP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTQQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTQS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTQT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTS:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTSP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTSQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTSS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTST:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTT:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTTP:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTTQ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTTS:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetTTTT:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWW:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWWZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWX:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWXZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWY:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWYZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZ:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetWZZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXW:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXWZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXX:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXXZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXY:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXYZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZ:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetXZZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYW:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYWZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYX:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYXZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYY:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYYZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZ:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetYZZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZW:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZWZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZX:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZXZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZY:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZYZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZ:TVector2; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZW:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZWW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZWX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZWY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZWZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZX:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZXW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZXX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZXY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZXZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZY:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZYW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZYX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZYY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZYZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZZ:TVector3; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZZW:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZZX:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZZY:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
function GetZZZZ:TVector4; {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAB(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetABG(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetABGR(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetABR(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetABRG(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAG(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAGB(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAGBR(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAGR(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAGRB(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetAR(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetARB(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetARBG(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetARG(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetARGB(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBA(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBAG(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBAGR(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBAR(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBARG(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBG(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBGA(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBGAR(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBGR(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBGRA(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBR(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBRA(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBRAG(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBRG(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetBRGA(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGA(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGAB(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGABR(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGAR(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGARB(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGB(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGBA(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGBAR(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGBR(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGBRA(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGR(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGRA(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGRAB(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGRB(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetGRBA(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPQ(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPQS(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPQST(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPQT(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPQTS(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPS(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPSQ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPSQT(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPST(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPSTQ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPT(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPTQ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPTQS(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPTS(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetPTSQ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQP(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQPS(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQPST(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQPT(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQPTS(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQS(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQSP(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQSPT(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQST(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQSTP(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQT(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQTP(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQTPS(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQTS(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetQTSP(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRA(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRAB(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRABG(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRAG(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRAGB(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRB(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRBA(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRBAG(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRBG(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRBGA(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRG(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRGA(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRGAB(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRGB(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetRGBA(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSP(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSPQ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSPQT(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSPT(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSPTQ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSQ(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSQP(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSQPT(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSQT(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSQTP(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetST(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSTP(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSTPQ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSTQ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetSTQP(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTP(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTPQ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTPQS(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTPS(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTPSQ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTQ(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTQP(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTQPS(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTQS(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTQSP(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTS(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTSP(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTSPQ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTSQ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetTSQP(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWX(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWXY(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWXYZ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWXZ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWXZY(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWY(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWYX(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWYXZ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWYZ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWYZX(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWZ(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWZX(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWZXY(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWZY(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetWZYX(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXW(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXWY(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXWYZ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXWZ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXWZY(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXY(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXYW(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXYWZ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXYZ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXYZW(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZ(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZW(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZWY(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZY(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetXZYW(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYW(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYWX(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYWXZ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYWZ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYWZX(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYX(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYXW(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYXWZ(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYXZ(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYXZW(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZ(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZW(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZWX(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZX(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetYZXW(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZW(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZWX(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZWXY(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZWY(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZWYX(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZX(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZXW(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZXWY(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZXY(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZXYW(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZY(const pValue:TVector2); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZYW(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZYWX(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZYX(const pValue:TVector3); {$ifdef CAN_INLINE}inline;{$endif}
procedure SetZYXW(const pValue:TVector4); {$ifdef CAN_INLINE}inline;{$endif}
public
property aa:TVector2 read GetAA;
property aaa:TVector3 read GetAAA;
property aaaa:TVector4 read GetAAAA;
property aaab:TVector4 read GetAAAB;
property aaag:TVector4 read GetAAAG;
property aaar:TVector4 read GetAAAR;
property aab:TVector3 read GetAAB;
property aaba:TVector4 read GetAABA;
property aabb:TVector4 read GetAABB;
property aabg:TVector4 read GetAABG;
property aabr:TVector4 read GetAABR;
property aag:TVector3 read GetAAG;
property aaga:TVector4 read GetAAGA;
property aagb:TVector4 read GetAAGB;
property aagg:TVector4 read GetAAGG;
property aagr:TVector4 read GetAAGR;
property aar:TVector3 read GetAAR;
property aara:TVector4 read GetAARA;
property aarb:TVector4 read GetAARB;
property aarg:TVector4 read GetAARG;
property aarr:TVector4 read GetAARR;
property ab:TVector2 read GetAB write SetAB;
property aba:TVector3 read GetABA;
property abaa:TVector4 read GetABAA;
property abab:TVector4 read GetABAB;
property abag:TVector4 read GetABAG;
property abar:TVector4 read GetABAR;
property abb:TVector3 read GetABB;
property abba:TVector4 read GetABBA;
property abbb:TVector4 read GetABBB;
property abbg:TVector4 read GetABBG;
property abbr:TVector4 read GetABBR;
property abg:TVector3 read GetABG write SetABG;
property abga:TVector4 read GetABGA;
property abgb:TVector4 read GetABGB;
property abgg:TVector4 read GetABGG;
property abgr:TVector4 read GetABGR write SetABGR;
property abr:TVector3 read GetABR write SetABR;
property abra:TVector4 read GetABRA;
property abrb:TVector4 read GetABRB;
property abrg:TVector4 read GetABRG write SetABRG;
property abrr:TVector4 read GetABRR;
property ag:TVector2 read GetAG write SetAG;
property aga:TVector3 read GetAGA;
property agaa:TVector4 read GetAGAA;
property agab:TVector4 read GetAGAB;
property agag:TVector4 read GetAGAG;
property agar:TVector4 read GetAGAR;
property agb:TVector3 read GetAGB write SetAGB;
property agba:TVector4 read GetAGBA;
property agbb:TVector4 read GetAGBB;
property agbg:TVector4 read GetAGBG;
property agbr:TVector4 read GetAGBR write SetAGBR;
property agg:TVector3 read GetAGG;
property agga:TVector4 read GetAGGA;
property aggb:TVector4 read GetAGGB;
property aggg:TVector4 read GetAGGG;
property aggr:TVector4 read GetAGGR;
property agr:TVector3 read GetAGR write SetAGR;
property agra:TVector4 read GetAGRA;
property agrb:TVector4 read GetAGRB write SetAGRB;
property agrg:TVector4 read GetAGRG;
property agrr:TVector4 read GetAGRR;
property ar:TVector2 read GetAR write SetAR;
property ara:TVector3 read GetARA;
property araa:TVector4 read GetARAA;
property arab:TVector4 read GetARAB;
property arag:TVector4 read GetARAG;
property arar:TVector4 read GetARAR;
property arb:TVector3 read GetARB write SetARB;
property arba:TVector4 read GetARBA;
property arbb:TVector4 read GetARBB;
property arbg:TVector4 read GetARBG write SetARBG;
property arbr:TVector4 read GetARBR;
property arg:TVector3 read GetARG write SetARG;
property arga:TVector4 read GetARGA;
property argb:TVector4 read GetARGB write SetARGB;
property argg:TVector4 read GetARGG;
property argr:TVector4 read GetARGR;
property arr:TVector3 read GetARR;
property arra:TVector4 read GetARRA;
property arrb:TVector4 read GetARRB;
property arrg:TVector4 read GetARRG;
property arrr:TVector4 read GetARRR;
property ba:TVector2 read GetBA write SetBA;
property baa:TVector3 read GetBAA;
property baaa:TVector4 read GetBAAA;
property baab:TVector4 read GetBAAB;
property baag:TVector4 read GetBAAG;
property baar:TVector4 read GetBAAR;
property bab:TVector3 read GetBAB;
property baba:TVector4 read GetBABA;
property babb:TVector4 read GetBABB;
property babg:TVector4 read GetBABG;
property babr:TVector4 read GetBABR;
property bag:TVector3 read GetBAG write SetBAG;
property baga:TVector4 read GetBAGA;
property bagb:TVector4 read GetBAGB;
property bagg:TVector4 read GetBAGG;
property bagr:TVector4 read GetBAGR write SetBAGR;
property bar:TVector3 read GetBAR write SetBAR;
property bara:TVector4 read GetBARA;
property barb:TVector4 read GetBARB;
property barg:TVector4 read GetBARG write SetBARG;
property barr:TVector4 read GetBARR;
property bb:TVector2 read GetBB;
property bba:TVector3 read GetBBA;
property bbaa:TVector4 read GetBBAA;
property bbab:TVector4 read GetBBAB;
property bbag:TVector4 read GetBBAG;
property bbar:TVector4 read GetBBAR;
property bbb:TVector3 read GetBBB;
property bbba:TVector4 read GetBBBA;
property bbbb:TVector4 read GetBBBB;
property bbbg:TVector4 read GetBBBG;
property bbbr:TVector4 read GetBBBR;
property bbg:TVector3 read GetBBG;
property bbga:TVector4 read GetBBGA;
property bbgb:TVector4 read GetBBGB;
property bbgg:TVector4 read GetBBGG;
property bbgr:TVector4 read GetBBGR;
property bbr:TVector3 read GetBBR;
property bbra:TVector4 read GetBBRA;
property bbrb:TVector4 read GetBBRB;
property bbrg:TVector4 read GetBBRG;
property bbrr:TVector4 read GetBBRR;
property bg:TVector2 read GetBG write SetBG;
property bga:TVector3 read GetBGA write SetBGA;
property bgaa:TVector4 read GetBGAA;
property bgab:TVector4 read GetBGAB;
property bgag:TVector4 read GetBGAG;
property bgar:TVector4 read GetBGAR write SetBGAR;
property bgb:TVector3 read GetBGB;
property bgba:TVector4 read GetBGBA;
property bgbb:TVector4 read GetBGBB;
property bgbg:TVector4 read GetBGBG;
property bgbr:TVector4 read GetBGBR;
property bgg:TVector3 read GetBGG;
property bgga:TVector4 read GetBGGA;
property bggb:TVector4 read GetBGGB;
property bggg:TVector4 read GetBGGG;
property bggr:TVector4 read GetBGGR;
property bgr:TVector3 read GetBGR write SetBGR;
property bgra:TVector4 read GetBGRA write SetBGRA;
property bgrb:TVector4 read GetBGRB;
property bgrg:TVector4 read GetBGRG;
property bgrr:TVector4 read GetBGRR;
property br:TVector2 read GetBR write SetBR;
property bra:TVector3 read GetBRA write SetBRA;
property braa:TVector4 read GetBRAA;
property brab:TVector4 read GetBRAB;
property brag:TVector4 read GetBRAG write SetBRAG;
property brar:TVector4 read GetBRAR;
property brb:TVector3 read GetBRB;
property brba:TVector4 read GetBRBA;
property brbb:TVector4 read GetBRBB;
property brbg:TVector4 read GetBRBG;
property brbr:TVector4 read GetBRBR;
property brg:TVector3 read GetBRG write SetBRG;
property brga:TVector4 read GetBRGA write SetBRGA;
property brgb:TVector4 read GetBRGB;
property brgg:TVector4 read GetBRGG;
property brgr:TVector4 read GetBRGR;
property brr:TVector3 read GetBRR;
property brra:TVector4 read GetBRRA;
property brrb:TVector4 read GetBRRB;
property brrg:TVector4 read GetBRRG;
property brrr:TVector4 read GetBRRR;
property ga:TVector2 read GetGA write SetGA;
property gaa:TVector3 read GetGAA;
property gaaa:TVector4 read GetGAAA;
property gaab:TVector4 read GetGAAB;
property gaag:TVector4 read GetGAAG;
property gaar:TVector4 read GetGAAR;
property gab:TVector3 read GetGAB write SetGAB;
property gaba:TVector4 read GetGABA;
property gabb:TVector4 read GetGABB;
property gabg:TVector4 read GetGABG;
property gabr:TVector4 read GetGABR write SetGABR;
property gag:TVector3 read GetGAG;
property gaga:TVector4 read GetGAGA;
property gagb:TVector4 read GetGAGB;
property gagg:TVector4 read GetGAGG;
property gagr:TVector4 read GetGAGR;
property gar:TVector3 read GetGAR write SetGAR;
property gara:TVector4 read GetGARA;
property garb:TVector4 read GetGARB write SetGARB;
property garg:TVector4 read GetGARG;
property garr:TVector4 read GetGARR;
property gb:TVector2 read GetGB write SetGB;
property gba:TVector3 read GetGBA write SetGBA;
property gbaa:TVector4 read GetGBAA;
property gbab:TVector4 read GetGBAB;
property gbag:TVector4 read GetGBAG;
property gbar:TVector4 read GetGBAR write SetGBAR;
property gbb:TVector3 read GetGBB;
property gbba:TVector4 read GetGBBA;
property gbbb:TVector4 read GetGBBB;
property gbbg:TVector4 read GetGBBG;
property gbbr:TVector4 read GetGBBR;
property gbg:TVector3 read GetGBG;
property gbga:TVector4 read GetGBGA;
property gbgb:TVector4 read GetGBGB;
property gbgg:TVector4 read GetGBGG;
property gbgr:TVector4 read GetGBGR;
property gbr:TVector3 read GetGBR write SetGBR;
property gbra:TVector4 read GetGBRA write SetGBRA;
property gbrb:TVector4 read GetGBRB;
property gbrg:TVector4 read GetGBRG;
property gbrr:TVector4 read GetGBRR;
property gg:TVector2 read GetGG;
property gga:TVector3 read GetGGA;
property ggaa:TVector4 read GetGGAA;
property ggab:TVector4 read GetGGAB;
property ggag:TVector4 read GetGGAG;
property ggar:TVector4 read GetGGAR;
property ggb:TVector3 read GetGGB;
property ggba:TVector4 read GetGGBA;
property ggbb:TVector4 read GetGGBB;
property ggbg:TVector4 read GetGGBG;
property ggbr:TVector4 read GetGGBR;
property ggg:TVector3 read GetGGG;
property ggga:TVector4 read GetGGGA;
property gggb:TVector4 read GetGGGB;
property gggg:TVector4 read GetGGGG;
property gggr:TVector4 read GetGGGR;
property ggr:TVector3 read GetGGR;
property ggra:TVector4 read GetGGRA;
property ggrb:TVector4 read GetGGRB;
property ggrg:TVector4 read GetGGRG;
property ggrr:TVector4 read GetGGRR;
property gr:TVector2 read GetGR write SetGR;
property gra:TVector3 read GetGRA write SetGRA;
property graa:TVector4 read GetGRAA;
property grab:TVector4 read GetGRAB write SetGRAB;
property grag:TVector4 read GetGRAG;
property grar:TVector4 read GetGRAR;
property grb:TVector3 read GetGRB write SetGRB;
property grba:TVector4 read GetGRBA write SetGRBA;
property grbb:TVector4 read GetGRBB;
property grbg:TVector4 read GetGRBG;
property grbr:TVector4 read GetGRBR;
property grg:TVector3 read GetGRG;
property grga:TVector4 read GetGRGA;
property grgb:TVector4 read GetGRGB;
property grgg:TVector4 read GetGRGG;
property grgr:TVector4 read GetGRGR;
property grr:TVector3 read GetGRR;
property grra:TVector4 read GetGRRA;
property grrb:TVector4 read GetGRRB;
property grrg:TVector4 read GetGRRG;
property grrr:TVector4 read GetGRRR;
property pp:TVector2 read GetPP;
property ppp:TVector3 read GetPPP;
property pppp:TVector4 read GetPPPP;
property pppq:TVector4 read GetPPPQ;
property ppps:TVector4 read GetPPPS;
property pppt:TVector4 read GetPPPT;
property ppq:TVector3 read GetPPQ;
property ppqp:TVector4 read GetPPQP;
property ppqq:TVector4 read GetPPQQ;
property ppqs:TVector4 read GetPPQS;
property ppqt:TVector4 read GetPPQT;
property pps:TVector3 read GetPPS;
property ppsp:TVector4 read GetPPSP;
property ppsq:TVector4 read GetPPSQ;
property ppss:TVector4 read GetPPSS;
property ppst:TVector4 read GetPPST;
property ppt:TVector3 read GetPPT;
property pptp:TVector4 read GetPPTP;
property pptq:TVector4 read GetPPTQ;
property ppts:TVector4 read GetPPTS;
property pptt:TVector4 read GetPPTT;
property pq:TVector2 read GetPQ write SetPQ;
property pqp:TVector3 read GetPQP;
property pqpp:TVector4 read GetPQPP;
property pqpq:TVector4 read GetPQPQ;
property pqps:TVector4 read GetPQPS;
property pqpt:TVector4 read GetPQPT;
property pqq:TVector3 read GetPQQ;
property pqqp:TVector4 read GetPQQP;
property pqqq:TVector4 read GetPQQQ;
property pqqs:TVector4 read GetPQQS;
property pqqt:TVector4 read GetPQQT;
property pqs:TVector3 read GetPQS write SetPQS;
property pqsp:TVector4 read GetPQSP;
property pqsq:TVector4 read GetPQSQ;
property pqss:TVector4 read GetPQSS;
property pqst:TVector4 read GetPQST write SetPQST;
property pqt:TVector3 read GetPQT write SetPQT;
property pqtp:TVector4 read GetPQTP;
property pqtq:TVector4 read GetPQTQ;
property pqts:TVector4 read GetPQTS write SetPQTS;
property pqtt:TVector4 read GetPQTT;
property ps:TVector2 read GetPS write SetPS;
property psp:TVector3 read GetPSP;
property pspp:TVector4 read GetPSPP;
property pspq:TVector4 read GetPSPQ;
property psps:TVector4 read GetPSPS;
property pspt:TVector4 read GetPSPT;
property psq:TVector3 read GetPSQ write SetPSQ;
property psqp:TVector4 read GetPSQP;
property psqq:TVector4 read GetPSQQ;
property psqs:TVector4 read GetPSQS;
property psqt:TVector4 read GetPSQT write SetPSQT;
property pss:TVector3 read GetPSS;
property pssp:TVector4 read GetPSSP;
property pssq:TVector4 read GetPSSQ;
property psss:TVector4 read GetPSSS;
property psst:TVector4 read GetPSST;
property pst:TVector3 read GetPST write SetPST;
property pstp:TVector4 read GetPSTP;
property pstq:TVector4 read GetPSTQ write SetPSTQ;
property psts:TVector4 read GetPSTS;
property pstt:TVector4 read GetPSTT;
property pt:TVector2 read GetPT write SetPT;
property ptp:TVector3 read GetPTP;
property ptpp:TVector4 read GetPTPP;
property ptpq:TVector4 read GetPTPQ;
property ptps:TVector4 read GetPTPS;
property ptpt:TVector4 read GetPTPT;
property ptq:TVector3 read GetPTQ write SetPTQ;
property ptqp:TVector4 read GetPTQP;
property ptqq:TVector4 read GetPTQQ;
property ptqs:TVector4 read GetPTQS write SetPTQS;
property ptqt:TVector4 read GetPTQT;
property pts:TVector3 read GetPTS write SetPTS;
property ptsp:TVector4 read GetPTSP;
property ptsq:TVector4 read GetPTSQ write SetPTSQ;
property ptss:TVector4 read GetPTSS;
property ptst:TVector4 read GetPTST;
property ptt:TVector3 read GetPTT;
property pttp:TVector4 read GetPTTP;
property pttq:TVector4 read GetPTTQ;
property ptts:TVector4 read GetPTTS;
property pttt:TVector4 read GetPTTT;
property qp:TVector2 read GetQP write SetQP;
property qpp:TVector3 read GetQPP;
property qppp:TVector4 read GetQPPP;
property qppq:TVector4 read GetQPPQ;
property qpps:TVector4 read GetQPPS;
property qppt:TVector4 read GetQPPT;
property qpq:TVector3 read GetQPQ;
property qpqp:TVector4 read GetQPQP;
property qpqq:TVector4 read GetQPQQ;
property qpqs:TVector4 read GetQPQS;
property qpqt:TVector4 read GetQPQT;
property qps:TVector3 read GetQPS write SetQPS;
property qpsp:TVector4 read GetQPSP;
property qpsq:TVector4 read GetQPSQ;
property qpss:TVector4 read GetQPSS;
property qpst:TVector4 read GetQPST write SetQPST;
property qpt:TVector3 read GetQPT write SetQPT;
property qptp:TVector4 read GetQPTP;
property qptq:TVector4 read GetQPTQ;
property qpts:TVector4 read GetQPTS write SetQPTS;
property qptt:TVector4 read GetQPTT;
property qq:TVector2 read GetQQ;
property qqp:TVector3 read GetQQP;
property qqpp:TVector4 read GetQQPP;
property qqpq:TVector4 read GetQQPQ;
property qqps:TVector4 read GetQQPS;
property qqpt:TVector4 read GetQQPT;
property qqq:TVector3 read GetQQQ;
property qqqp:TVector4 read GetQQQP;
property qqqq:TVector4 read GetQQQQ;
property qqqs:TVector4 read GetQQQS;
property qqqt:TVector4 read GetQQQT;
property qqs:TVector3 read GetQQS;
property qqsp:TVector4 read GetQQSP;
property qqsq:TVector4 read GetQQSQ;
property qqss:TVector4 read GetQQSS;
property qqst:TVector4 read GetQQST;
property qqt:TVector3 read GetQQT;
property qqtp:TVector4 read GetQQTP;
property qqtq:TVector4 read GetQQTQ;
property qqts:TVector4 read GetQQTS;
property qqtt:TVector4 read GetQQTT;
property qs:TVector2 read GetQS write SetQS;
property qsp:TVector3 read GetQSP write SetQSP;
property qspp:TVector4 read GetQSPP;
property qspq:TVector4 read GetQSPQ;
property qsps:TVector4 read GetQSPS;
property qspt:TVector4 read GetQSPT write SetQSPT;
property qsq:TVector3 read GetQSQ;
property qsqp:TVector4 read GetQSQP;
property qsqq:TVector4 read GetQSQQ;
property qsqs:TVector4 read GetQSQS;
property qsqt:TVector4 read GetQSQT;
property qss:TVector3 read GetQSS;
property qssp:TVector4 read GetQSSP;
property qssq:TVector4 read GetQSSQ;
property qsss:TVector4 read GetQSSS;
property qsst:TVector4 read GetQSST;
property qst:TVector3 read GetQST write SetQST;
property qstp:TVector4 read GetQSTP write SetQSTP;
property qstq:TVector4 read GetQSTQ;
property qsts:TVector4 read GetQSTS;
property qstt:TVector4 read GetQSTT;
property qt:TVector2 read GetQT write SetQT;
property qtp:TVector3 read GetQTP write SetQTP;
property qtpp:TVector4 read GetQTPP;
property qtpq:TVector4 read GetQTPQ;
property qtps:TVector4 read GetQTPS write SetQTPS;
property qtpt:TVector4 read GetQTPT;
property qtq:TVector3 read GetQTQ;
property qtqp:TVector4 read GetQTQP;
property qtqq:TVector4 read GetQTQQ;
property qtqs:TVector4 read GetQTQS;
property qtqt:TVector4 read GetQTQT;
property qts:TVector3 read GetQTS write SetQTS;
property qtsp:TVector4 read GetQTSP write SetQTSP;
property qtsq:TVector4 read GetQTSQ;
property qtss:TVector4 read GetQTSS;
property qtst:TVector4 read GetQTST;
property qtt:TVector3 read GetQTT;
property qttp:TVector4 read GetQTTP;
property qttq:TVector4 read GetQTTQ;
property qtts:TVector4 read GetQTTS;
property qttt:TVector4 read GetQTTT;
property ra:TVector2 read GetRA write SetRA;
property raa:TVector3 read GetRAA;
property raaa:TVector4 read GetRAAA;
property raab:TVector4 read GetRAAB;
property raag:TVector4 read GetRAAG;
property raar:TVector4 read GetRAAR;
property rab:TVector3 read GetRAB write SetRAB;
property raba:TVector4 read GetRABA;
property rabb:TVector4 read GetRABB;
property rabg:TVector4 read GetRABG write SetRABG;
property rabr:TVector4 read GetRABR;
property rag:TVector3 read GetRAG write SetRAG;
property raga:TVector4 read GetRAGA;
property ragb:TVector4 read GetRAGB write SetRAGB;
property ragg:TVector4 read GetRAGG;
property ragr:TVector4 read GetRAGR;
property rar:TVector3 read GetRAR;
property rara:TVector4 read GetRARA;
property rarb:TVector4 read GetRARB;
property rarg:TVector4 read GetRARG;
property rarr:TVector4 read GetRARR;
property rb:TVector2 read GetRB write SetRB;
property rba:TVector3 read GetRBA write SetRBA;
property rbaa:TVector4 read GetRBAA;
property rbab:TVector4 read GetRBAB;
property rbag:TVector4 read GetRBAG write SetRBAG;
property rbar:TVector4 read GetRBAR;
property rbb:TVector3 read GetRBB;
property rbba:TVector4 read GetRBBA;
property rbbb:TVector4 read GetRBBB;
property rbbg:TVector4 read GetRBBG;
property rbbr:TVector4 read GetRBBR;
property rbg:TVector3 read GetRBG write SetRBG;
property rbga:TVector4 read GetRBGA write SetRBGA;
property rbgb:TVector4 read GetRBGB;
property rbgg:TVector4 read GetRBGG;
property rbgr:TVector4 read GetRBGR;
property rbr:TVector3 read GetRBR;
property rbra:TVector4 read GetRBRA;
property rbrb:TVector4 read GetRBRB;
property rbrg:TVector4 read GetRBRG;
property rbrr:TVector4 read GetRBRR;
property rg:TVector2 read GetRG write SetRG;
property rga:TVector3 read GetRGA write SetRGA;
property rgaa:TVector4 read GetRGAA;
property rgab:TVector4 read GetRGAB write SetRGAB;
property rgag:TVector4 read GetRGAG;
property rgar:TVector4 read GetRGAR;
property rgb:TVector3 read GetRGB write SetRGB;
property rgba:TVector4 read GetRGBA write SetRGBA;
property rgbb:TVector4 read GetRGBB;
property rgbg:TVector4 read GetRGBG;
property rgbr:TVector4 read GetRGBR;
property rgg:TVector3 read GetRGG;
property rgga:TVector4 read GetRGGA;
property rggb:TVector4 read GetRGGB;
property rggg:TVector4 read GetRGGG;
property rggr:TVector4 read GetRGGR;
property rgr:TVector3 read GetRGR;
property rgra:TVector4 read GetRGRA;
property rgrb:TVector4 read GetRGRB;
property rgrg:TVector4 read GetRGRG;
property rgrr:TVector4 read GetRGRR;
property rr:TVector2 read GetRR;
property rra:TVector3 read GetRRA;
property rraa:TVector4 read GetRRAA;
property rrab:TVector4 read GetRRAB;
property rrag:TVector4 read GetRRAG;
property rrar:TVector4 read GetRRAR;
property rrb:TVector3 read GetRRB;
property rrba:TVector4 read GetRRBA;
property rrbb:TVector4 read GetRRBB;
property rrbg:TVector4 read GetRRBG;
property rrbr:TVector4 read GetRRBR;
property rrg:TVector3 read GetRRG;
property rrga:TVector4 read GetRRGA;
property rrgb:TVector4 read GetRRGB;
property rrgg:TVector4 read GetRRGG;
property rrgr:TVector4 read GetRRGR;
property rrr:TVector3 read GetRRR;
property rrra:TVector4 read GetRRRA;
property rrrb:TVector4 read GetRRRB;
property rrrg:TVector4 read GetRRRG;
property rrrr:TVector4 read GetRRRR;
property sp:TVector2 read GetSP write SetSP;
property spp:TVector3 read GetSPP;
property sppp:TVector4 read GetSPPP;
property sppq:TVector4 read GetSPPQ;
property spps:TVector4 read GetSPPS;
property sppt:TVector4 read GetSPPT;
property spq:TVector3 read GetSPQ write SetSPQ;
property spqp:TVector4 read GetSPQP;
property spqq:TVector4 read GetSPQQ;
property spqs:TVector4 read GetSPQS;
property spqt:TVector4 read GetSPQT write SetSPQT;
property sps:TVector3 read GetSPS;
property spsp:TVector4 read GetSPSP;
property spsq:TVector4 read GetSPSQ;
property spss:TVector4 read GetSPSS;
property spst:TVector4 read GetSPST;
property spt:TVector3 read GetSPT write SetSPT;
property sptp:TVector4 read GetSPTP;
property sptq:TVector4 read GetSPTQ write SetSPTQ;
property spts:TVector4 read GetSPTS;
property sptt:TVector4 read GetSPTT;
property sq:TVector2 read GetSQ write SetSQ;
property sqp:TVector3 read GetSQP write SetSQP;
property sqpp:TVector4 read GetSQPP;
property sqpq:TVector4 read GetSQPQ;
property sqps:TVector4 read GetSQPS;
property sqpt:TVector4 read GetSQPT write SetSQPT;
property sqq:TVector3 read GetSQQ;
property sqqp:TVector4 read GetSQQP;
property sqqq:TVector4 read GetSQQQ;
property sqqs:TVector4 read GetSQQS;
property sqqt:TVector4 read GetSQQT;
property sqs:TVector3 read GetSQS;
property sqsp:TVector4 read GetSQSP;
property sqsq:TVector4 read GetSQSQ;
property sqss:TVector4 read GetSQSS;
property sqst:TVector4 read GetSQST;
property sqt:TVector3 read GetSQT write SetSQT;
property sqtp:TVector4 read GetSQTP write SetSQTP;
property sqtq:TVector4 read GetSQTQ;
property sqts:TVector4 read GetSQTS;
property sqtt:TVector4 read GetSQTT;
property ss:TVector2 read GetSS;
property ssp:TVector3 read GetSSP;
property sspp:TVector4 read GetSSPP;
property sspq:TVector4 read GetSSPQ;
property ssps:TVector4 read GetSSPS;
property sspt:TVector4 read GetSSPT;
property ssq:TVector3 read GetSSQ;
property ssqp:TVector4 read GetSSQP;
property ssqq:TVector4 read GetSSQQ;
property ssqs:TVector4 read GetSSQS;
property ssqt:TVector4 read GetSSQT;
property sss:TVector3 read GetSSS;
property sssp:TVector4 read GetSSSP;
property sssq:TVector4 read GetSSSQ;
property ssss:TVector4 read GetSSSS;
property ssst:TVector4 read GetSSST;
property sst:TVector3 read GetSST;
property sstp:TVector4 read GetSSTP;
property sstq:TVector4 read GetSSTQ;
property ssts:TVector4 read GetSSTS;
property sstt:TVector4 read GetSSTT;
property st:TVector2 read GetST write SetST;
property stp:TVector3 read GetSTP write SetSTP;
property stpp:TVector4 read GetSTPP;
property stpq:TVector4 read GetSTPQ write SetSTPQ;
property stps:TVector4 read GetSTPS;
property stpt:TVector4 read GetSTPT;
property stq:TVector3 read GetSTQ write SetSTQ;
property stqp:TVector4 read GetSTQP write SetSTQP;
property stqq:TVector4 read GetSTQQ;
property stqs:TVector4 read GetSTQS;
property stqt:TVector4 read GetSTQT;
property sts:TVector3 read GetSTS;
property stsp:TVector4 read GetSTSP;
property stsq:TVector4 read GetSTSQ;
property stss:TVector4 read GetSTSS;
property stst:TVector4 read GetSTST;
property stt:TVector3 read GetSTT;
property sttp:TVector4 read GetSTTP;
property sttq:TVector4 read GetSTTQ;
property stts:TVector4 read GetSTTS;
property sttt:TVector4 read GetSTTT;
property tp:TVector2 read GetTP write SetTP;
property tpp:TVector3 read GetTPP;
property tppp:TVector4 read GetTPPP;
property tppq:TVector4 read GetTPPQ;
property tpps:TVector4 read GetTPPS;
property tppt:TVector4 read GetTPPT;
property tpq:TVector3 read GetTPQ write SetTPQ;
property tpqp:TVector4 read GetTPQP;
property tpqq:TVector4 read GetTPQQ;
property tpqs:TVector4 read GetTPQS write SetTPQS;
property tpqt:TVector4 read GetTPQT;
property tps:TVector3 read GetTPS write SetTPS;
property tpsp:TVector4 read GetTPSP;
property tpsq:TVector4 read GetTPSQ write SetTPSQ;
property tpss:TVector4 read GetTPSS;
property tpst:TVector4 read GetTPST;
property tpt:TVector3 read GetTPT;
property tptp:TVector4 read GetTPTP;
property tptq:TVector4 read GetTPTQ;
property tpts:TVector4 read GetTPTS;
property tptt:TVector4 read GetTPTT;
property tq:TVector2 read GetTQ write SetTQ;
property tqp:TVector3 read GetTQP write SetTQP;
property tqpp:TVector4 read GetTQPP;
property tqpq:TVector4 read GetTQPQ;
property tqps:TVector4 read GetTQPS write SetTQPS;
property tqpt:TVector4 read GetTQPT;
property tqq:TVector3 read GetTQQ;
property tqqp:TVector4 read GetTQQP;
property tqqq:TVector4 read GetTQQQ;
property tqqs:TVector4 read GetTQQS;
property tqqt:TVector4 read GetTQQT;
property tqs:TVector3 read GetTQS write SetTQS;
property tqsp:TVector4 read GetTQSP write SetTQSP;
property tqsq:TVector4 read GetTQSQ;
property tqss:TVector4 read GetTQSS;
property tqst:TVector4 read GetTQST;
property tqt:TVector3 read GetTQT;
property tqtp:TVector4 read GetTQTP;
property tqtq:TVector4 read GetTQTQ;
property tqts:TVector4 read GetTQTS;
property tqtt:TVector4 read GetTQTT;
property ts:TVector2 read GetTS write SetTS;
property tsp:TVector3 read GetTSP write SetTSP;
property tspp:TVector4 read GetTSPP;
property tspq:TVector4 read GetTSPQ write SetTSPQ;
property tsps:TVector4 read GetTSPS;
property tspt:TVector4 read GetTSPT;
property tsq:TVector3 read GetTSQ write SetTSQ;
property tsqp:TVector4 read GetTSQP write SetTSQP;
property tsqq:TVector4 read GetTSQQ;
property tsqs:TVector4 read GetTSQS;
property tsqt:TVector4 read GetTSQT;
property tss:TVector3 read GetTSS;
property tssp:TVector4 read GetTSSP;
property tssq:TVector4 read GetTSSQ;
property tsss:TVector4 read GetTSSS;
property tsst:TVector4 read GetTSST;
property tst:TVector3 read GetTST;
property tstp:TVector4 read GetTSTP;
property tstq:TVector4 read GetTSTQ;
property tsts:TVector4 read GetTSTS;
property tstt:TVector4 read GetTSTT;
property tt:TVector2 read GetTT;
property ttp:TVector3 read GetTTP;
property ttpp:TVector4 read GetTTPP;
property ttpq:TVector4 read GetTTPQ;
property ttps:TVector4 read GetTTPS;
property ttpt:TVector4 read GetTTPT;
property ttq:TVector3 read GetTTQ;
property ttqp:TVector4 read GetTTQP;
property ttqq:TVector4 read GetTTQQ;
property ttqs:TVector4 read GetTTQS;
property ttqt:TVector4 read GetTTQT;
property tts:TVector3 read GetTTS;
property ttsp:TVector4 read GetTTSP;
property ttsq:TVector4 read GetTTSQ;
property ttss:TVector4 read GetTTSS;
property ttst:TVector4 read GetTTST;
property ttt:TVector3 read GetTTT;
property tttp:TVector4 read GetTTTP;
property tttq:TVector4 read GetTTTQ;
property ttts:TVector4 read GetTTTS;
property tttt:TVector4 read GetTTTT;
property ww:TVector2 read GetWW;
property www:TVector3 read GetWWW;
property wwww:TVector4 read GetWWWW;
property wwwx:TVector4 read GetWWWX;
property wwwy:TVector4 read GetWWWY;
property wwwz:TVector4 read GetWWWZ;
property wwx:TVector3 read GetWWX;
property wwxw:TVector4 read GetWWXW;
property wwxx:TVector4 read GetWWXX;
property wwxy:TVector4 read GetWWXY;
property wwxz:TVector4 read GetWWXZ;
property wwy:TVector3 read GetWWY;
property wwyw:TVector4 read GetWWYW;
property wwyx:TVector4 read GetWWYX;
property wwyy:TVector4 read GetWWYY;
property wwyz:TVector4 read GetWWYZ;
property wwz:TVector3 read GetWWZ;
property wwzw:TVector4 read GetWWZW;
property wwzx:TVector4 read GetWWZX;
property wwzy:TVector4 read GetWWZY;
property wwzz:TVector4 read GetWWZZ;
property wx:TVector2 read GetWX write SetWX;
property wxw:TVector3 read GetWXW;
property wxww:TVector4 read GetWXWW;
property wxwx:TVector4 read GetWXWX;
property wxwy:TVector4 read GetWXWY;
property wxwz:TVector4 read GetWXWZ;
property wxx:TVector3 read GetWXX;
property wxxw:TVector4 read GetWXXW;
property wxxx:TVector4 read GetWXXX;
property wxxy:TVector4 read GetWXXY;
property wxxz:TVector4 read GetWXXZ;
property wxy:TVector3 read GetWXY write SetWXY;
property wxyw:TVector4 read GetWXYW;
property wxyx:TVector4 read GetWXYX;
property wxyy:TVector4 read GetWXYY;
property wxyz:TVector4 read GetWXYZ write SetWXYZ;
property wxz:TVector3 read GetWXZ write SetWXZ;
property wxzw:TVector4 read GetWXZW;
property wxzx:TVector4 read GetWXZX;
property wxzy:TVector4 read GetWXZY write SetWXZY;
property wxzz:TVector4 read GetWXZZ;
property wy:TVector2 read GetWY write SetWY;
property wyw:TVector3 read GetWYW;
property wyww:TVector4 read GetWYWW;
property wywx:TVector4 read GetWYWX;
property wywy:TVector4 read GetWYWY;
property wywz:TVector4 read GetWYWZ;
property wyx:TVector3 read GetWYX write SetWYX;
property wyxw:TVector4 read GetWYXW;
property wyxx:TVector4 read GetWYXX;
property wyxy:TVector4 read GetWYXY;
property wyxz:TVector4 read GetWYXZ write SetWYXZ;
property wyy:TVector3 read GetWYY;
property wyyw:TVector4 read GetWYYW;
property wyyx:TVector4 read GetWYYX;
property wyyy:TVector4 read GetWYYY;
property wyyz:TVector4 read GetWYYZ;
property wyz:TVector3 read GetWYZ write SetWYZ;
property wyzw:TVector4 read GetWYZW;
property wyzx:TVector4 read GetWYZX write SetWYZX;
property wyzy:TVector4 read GetWYZY;
property wyzz:TVector4 read GetWYZZ;
property wz:TVector2 read GetWZ write SetWZ;
property wzw:TVector3 read GetWZW;
property wzww:TVector4 read GetWZWW;
property wzwx:TVector4 read GetWZWX;
property wzwy:TVector4 read GetWZWY;
property wzwz:TVector4 read GetWZWZ;
property wzx:TVector3 read GetWZX write SetWZX;
property wzxw:TVector4 read GetWZXW;
property wzxx:TVector4 read GetWZXX;
property wzxy:TVector4 read GetWZXY write SetWZXY;
property wzxz:TVector4 read GetWZXZ;
property wzy:TVector3 read GetWZY write SetWZY;
property wzyw:TVector4 read GetWZYW;
property wzyx:TVector4 read GetWZYX write SetWZYX;
property wzyy:TVector4 read GetWZYY;
property wzyz:TVector4 read GetWZYZ;
property wzz:TVector3 read GetWZZ;
property wzzw:TVector4 read GetWZZW;
property wzzx:TVector4 read GetWZZX;
property wzzy:TVector4 read GetWZZY;
property wzzz:TVector4 read GetWZZZ;
property xw:TVector2 read GetXW write SetXW;
property xww:TVector3 read GetXWW;
property xwww:TVector4 read GetXWWW;
property xwwx:TVector4 read GetXWWX;
property xwwy:TVector4 read GetXWWY;
property xwwz:TVector4 read GetXWWZ;
property xwx:TVector3 read GetXWX;
property xwxw:TVector4 read GetXWXW;
property xwxx:TVector4 read GetXWXX;
property xwxy:TVector4 read GetXWXY;
property xwxz:TVector4 read GetXWXZ;
property xwy:TVector3 read GetXWY write SetXWY;
property xwyw:TVector4 read GetXWYW;
property xwyx:TVector4 read GetXWYX;
property xwyy:TVector4 read GetXWYY;
property xwyz:TVector4 read GetXWYZ write SetXWYZ;
property xwz:TVector3 read GetXWZ write SetXWZ;
property xwzw:TVector4 read GetXWZW;
property xwzx:TVector4 read GetXWZX;
property xwzy:TVector4 read GetXWZY write SetXWZY;
property xwzz:TVector4 read GetXWZZ;
property xx:TVector2 read GetXX;
property xxw:TVector3 read GetXXW;
property xxww:TVector4 read GetXXWW;
property xxwx:TVector4 read GetXXWX;
property xxwy:TVector4 read GetXXWY;
property xxwz:TVector4 read GetXXWZ;
property xxx:TVector3 read GetXXX;
property xxxw:TVector4 read GetXXXW;
property xxxx:TVector4 read GetXXXX;
property xxxy:TVector4 read GetXXXY;
property xxxz:TVector4 read GetXXXZ;
property xxy:TVector3 read GetXXY;
property xxyw:TVector4 read GetXXYW;
property xxyx:TVector4 read GetXXYX;
property xxyy:TVector4 read GetXXYY;
property xxyz:TVector4 read GetXXYZ;
property xxz:TVector3 read GetXXZ;
property xxzw:TVector4 read GetXXZW;
property xxzx:TVector4 read GetXXZX;
property xxzy:TVector4 read GetXXZY;
property xxzz:TVector4 read GetXXZZ;
property xy:TVector2 read GetXY write SetXY;
property xyw:TVector3 read GetXYW write SetXYW;
property xyww:TVector4 read GetXYWW;
property xywx:TVector4 read GetXYWX;
property xywy:TVector4 read GetXYWY;
property xywz:TVector4 read GetXYWZ write SetXYWZ;
property xyx:TVector3 read GetXYX;
property xyxw:TVector4 read GetXYXW;
property xyxx:TVector4 read GetXYXX;
property xyxy:TVector4 read GetXYXY;
property xyxz:TVector4 read GetXYXZ;
property xyy:TVector3 read GetXYY;
property xyyw:TVector4 read GetXYYW;
property xyyx:TVector4 read GetXYYX;
property xyyy:TVector4 read GetXYYY;
property xyyz:TVector4 read GetXYYZ;
property xyz:TVector3 read GetXYZ write SetXYZ;
property xyzw:TVector4 read GetXYZW write SetXYZW;
property xyzx:TVector4 read GetXYZX;
property xyzy:TVector4 read GetXYZY;
property xyzz:TVector4 read GetXYZZ;
property xz:TVector2 read GetXZ write SetXZ;
property xzw:TVector3 read GetXZW write SetXZW;
property xzww:TVector4 read GetXZWW;
property xzwx:TVector4 read GetXZWX;
property xzwy:TVector4 read GetXZWY write SetXZWY;
property xzwz:TVector4 read GetXZWZ;
property xzx:TVector3 read GetXZX;
property xzxw:TVector4 read GetXZXW;
property xzxx:TVector4 read GetXZXX;
property xzxy:TVector4 read GetXZXY;
property xzxz:TVector4 read GetXZXZ;
property xzy:TVector3 read GetXZY write SetXZY;
property xzyw:TVector4 read GetXZYW write SetXZYW;
property xzyx:TVector4 read GetXZYX;
property xzyy:TVector4 read GetXZYY;
property xzyz:TVector4 read GetXZYZ;
property xzz:TVector3 read GetXZZ;
property xzzw:TVector4 read GetXZZW;
property xzzx:TVector4 read GetXZZX;
property xzzy:TVector4 read GetXZZY;
property xzzz:TVector4 read GetXZZZ;
property yw:TVector2 read GetYW write SetYW;
property yww:TVector3 read GetYWW;
property ywww:TVector4 read GetYWWW;
property ywwx:TVector4 read GetYWWX;
property ywwy:TVector4 read GetYWWY;
property ywwz:TVector4 read GetYWWZ;
property ywx:TVector3 read GetYWX write SetYWX;
property ywxw:TVector4 read GetYWXW;
property ywxx:TVector4 read GetYWXX;
property ywxy:TVector4 read GetYWXY;
property ywxz:TVector4 read GetYWXZ write SetYWXZ;
property ywy:TVector3 read GetYWY;
property ywyw:TVector4 read GetYWYW;
property ywyx:TVector4 read GetYWYX;
property ywyy:TVector4 read GetYWYY;
property ywyz:TVector4 read GetYWYZ;
property ywz:TVector3 read GetYWZ write SetYWZ;
property ywzw:TVector4 read GetYWZW;
property ywzx:TVector4 read GetYWZX write SetYWZX;
property ywzy:TVector4 read GetYWZY;
property ywzz:TVector4 read GetYWZZ;
property yx:TVector2 read GetYX write SetYX;
property yxw:TVector3 read GetYXW write SetYXW;
property yxww:TVector4 read GetYXWW;
property yxwx:TVector4 read GetYXWX;
property yxwy:TVector4 read GetYXWY;
property yxwz:TVector4 read GetYXWZ write SetYXWZ;
property yxx:TVector3 read GetYXX;
property yxxw:TVector4 read GetYXXW;
property yxxx:TVector4 read GetYXXX;
property yxxy:TVector4 read GetYXXY;
property yxxz:TVector4 read GetYXXZ;
property yxy:TVector3 read GetYXY;
property yxyw:TVector4 read GetYXYW;
property yxyx:TVector4 read GetYXYX;
property yxyy:TVector4 read GetYXYY;
property yxyz:TVector4 read GetYXYZ;
property yxz:TVector3 read GetYXZ write SetYXZ;
property yxzw:TVector4 read GetYXZW write SetYXZW;
property yxzx:TVector4 read GetYXZX;
property yxzy:TVector4 read GetYXZY;
property yxzz:TVector4 read GetYXZZ;
property yy:TVector2 read GetYY;
property yyw:TVector3 read GetYYW;
property yyww:TVector4 read GetYYWW;
property yywx:TVector4 read GetYYWX;
property yywy:TVector4 read GetYYWY;
property yywz:TVector4 read GetYYWZ;
property yyx:TVector3 read GetYYX;
property yyxw:TVector4 read GetYYXW;
property yyxx:TVector4 read GetYYXX;
property yyxy:TVector4 read GetYYXY;
property yyxz:TVector4 read GetYYXZ;
property yyy:TVector3 read GetYYY;
property yyyw:TVector4 read GetYYYW;
property yyyx:TVector4 read GetYYYX;
property yyyy:TVector4 read GetYYYY;
property yyyz:TVector4 read GetYYYZ;
property yyz:TVector3 read GetYYZ;
property yyzw:TVector4 read GetYYZW;
property yyzx:TVector4 read GetYYZX;
property yyzy:TVector4 read GetYYZY;
property yyzz:TVector4 read GetYYZZ;
property yz:TVector2 read GetYZ write SetYZ;
property yzw:TVector3 read GetYZW write SetYZW;
property yzww:TVector4 read GetYZWW;
property yzwx:TVector4 read GetYZWX write SetYZWX;
property yzwy:TVector4 read GetYZWY;
property yzwz:TVector4 read GetYZWZ;
property yzx:TVector3 read GetYZX write SetYZX;
property yzxw:TVector4 read GetYZXW write SetYZXW;
property yzxx:TVector4 read GetYZXX;
property yzxy:TVector4 read GetYZXY;
property yzxz:TVector4 read GetYZXZ;
property yzy:TVector3 read GetYZY;
property yzyw:TVector4 read GetYZYW;
property yzyx:TVector4 read GetYZYX;
property yzyy:TVector4 read GetYZYY;
property yzyz:TVector4 read GetYZYZ;
property yzz:TVector3 read GetYZZ;
property yzzw:TVector4 read GetYZZW;
property yzzx:TVector4 read GetYZZX;
property yzzy:TVector4 read GetYZZY;
property yzzz:TVector4 read GetYZZZ;
property zw:TVector2 read GetZW write SetZW;
property zww:TVector3 read GetZWW;
property zwww:TVector4 read GetZWWW;
property zwwx:TVector4 read GetZWWX;
property zwwy:TVector4 read GetZWWY;
property zwwz:TVector4 read GetZWWZ;
property zwx:TVector3 read GetZWX write SetZWX;
property zwxw:TVector4 read GetZWXW;
property zwxx:TVector4 read GetZWXX;
property zwxy:TVector4 read GetZWXY write SetZWXY;
property zwxz:TVector4 read GetZWXZ;
property zwy:TVector3 read GetZWY write SetZWY;
property zwyw:TVector4 read GetZWYW;
property zwyx:TVector4 read GetZWYX write SetZWYX;
property zwyy:TVector4 read GetZWYY;
property zwyz:TVector4 read GetZWYZ;
property zwz:TVector3 read GetZWZ;
property zwzw:TVector4 read GetZWZW;
property zwzx:TVector4 read GetZWZX;
property zwzy:TVector4 read GetZWZY;
property zwzz:TVector4 read GetZWZZ;
property zx:TVector2 read GetZX write SetZX;
property zxw:TVector3 read GetZXW write SetZXW;
property zxww:TVector4 read GetZXWW;
property zxwx:TVector4 read GetZXWX;
property zxwy:TVector4 read GetZXWY write SetZXWY;
property zxwz:TVector4 read GetZXWZ;
property zxx:TVector3 read GetZXX;
property zxxw:TVector4 read GetZXXW;
property zxxx:TVector4 read GetZXXX;
property zxxy:TVector4 read GetZXXY;
property zxxz:TVector4 read GetZXXZ;
property zxy:TVector3 read GetZXY write SetZXY;
property zxyw:TVector4 read GetZXYW write SetZXYW;
property zxyx:TVector4 read GetZXYX;
property zxyy:TVector4 read GetZXYY;
property zxyz:TVector4 read GetZXYZ;
property zxz:TVector3 read GetZXZ;
property zxzw:TVector4 read GetZXZW;
property zxzx:TVector4 read GetZXZX;
property zxzy:TVector4 read GetZXZY;
property zxzz:TVector4 read GetZXZZ;
property zy:TVector2 read GetZY write SetZY;
property zyw:TVector3 read GetZYW write SetZYW;
property zyww:TVector4 read GetZYWW;
property zywx:TVector4 read GetZYWX write SetZYWX;
property zywy:TVector4 read GetZYWY;
property zywz:TVector4 read GetZYWZ;
property zyx:TVector3 read GetZYX write SetZYX;
property zyxw:TVector4 read GetZYXW write SetZYXW;
property zyxx:TVector4 read GetZYXX;
property zyxy:TVector4 read GetZYXY;
property zyxz:TVector4 read GetZYXZ;
property zyy:TVector3 read GetZYY;
property zyyw:TVector4 read GetZYYW;
property zyyx:TVector4 read GetZYYX;
property zyyy:TVector4 read GetZYYY;
property zyyz:TVector4 read GetZYYZ;
property zyz:TVector3 read GetZYZ;
property zyzw:TVector4 read GetZYZW;
property zyzx:TVector4 read GetZYZX;
property zyzy:TVector4 read GetZYZY;
property zyzz:TVector4 read GetZYZZ;
property zz:TVector2 read GetZZ;
property zzw:TVector3 read GetZZW;
property zzww:TVector4 read GetZZWW;
property zzwx:TVector4 read GetZZWX;
property zzwy:TVector4 read GetZZWY;
property zzwz:TVector4 read GetZZWZ;
property zzx:TVector3 read GetZZX;
property zzxw:TVector4 read GetZZXW;
property zzxx:TVector4 read GetZZXX;
property zzxy:TVector4 read GetZZXY;
property zzxz:TVector4 read GetZZXZ;
property zzy:TVector3 read GetZZY;
property zzyw:TVector4 read GetZZYW;
property zzyx:TVector4 read GetZZYX;
property zzyy:TVector4 read GetZZYY;
property zzyz:TVector4 read GetZZYZ;
property zzz:TVector3 read GetZZZ;
property zzzw:TVector4 read GetZZZW;
property zzzx:TVector4 read GetZZZX;
property zzzy:TVector4 read GetZZZY;
property zzzz:TVector4 read GetZZZZ;
